redis/go-redis

command.go, commands.go, parser.go, pubsub_test.go
=> Better fix for pubsub numsub

cluster.go
=> Fixed redirects logic - 'max' means less that or equals to

cluster.go, pool.go, sentinel.go
=> Add reaper that closes idle connections to the cluster.

cluster.go, cluster_client_test.go, redis.go
=> Ensure slots are initialised. Return non-failing connections to pool

cluster_pipeline.go, multi.go, pipeline.go, redis.go
Just minor, but what do you think?
=> Simplify internal API

cluster_test.go, pool_test.go, redis_test.go
```
BenchmarkRedisClusterPing	   30000	     39906 ns/op
BenchmarkRedisPing	   50000	     33728 ns/op
```
=> Add very basic cluster benchmark. Cleanup other benchmarks.

pool.go
=> pool: gracefully close pool by giving users time to free connection.

cluster.go, cluster_test.go
Newly added test fails without the fix.
/cc @dim
=> cluster: don't reset command when there no attempts left.

command.go, conn.go, error.go, export_test.go, pipeline.go, pool.go, pubsub.go, redis.go, redis_test.go
Things to consider when reviewing this PR:
- we have MaxRetries and MaxRedirects. Merge them?
- MultiClient and PubSubClient don't auto-retry
- Pipelines are auto-retried. Should we?
=> Add auto-retry and MaxRetries option. Fixes #84.

.travis.yml, cluster_test.go, command_test.go, commands_test.go, example_test.go, main_test.go, multi_test.go, pipeline_test.go, pool_test.go, pubsub_test.go, redis.go, redis_test.go, sentinel_test.go
@dim is there anything you want to do before releasing v3 with ClusterClient?
=> Release redis.v3 beta.

cluster.go, example_test.go, sentinel.go
Example is probably too simple, but I have no ideas how to improve it.
=> Add basic example how to use Redis Cluster. Unify comments.

pool.go
Fixes
```
Test Panicked
conn not found in the list
/usr/local/go/src/pkg/runtime/panic.c:248
Full Stack Trace
(*connList).Replace: panic("conn not found in the list")
/home/travis/gopath/src/gopkg.in/redis.v3/pool.go:259 (0x4665dd)
(*connPool).Remove: return p.conns.Replace(cn, newcn)
/home/travis/gopath/src/gopkg.in/redis.v3/pool.go:397 (0x466f5a)
(*singleConnPool).remove: err := p.pool.Remove(p.cn)
/home/travis/gopath/src/gopkg.in/redis.v3/pool.go:432 (0x467242)
(*singleConnPool).Close: err = p.remove()
/home/travis/gopath/src/gopkg.in/redis.v3/redis.go:84 (0x4691d1)
(*baseClient).Close: return c.connPool.Close()
/home/travis/gopath/src/gopkg.in/redis.v3/pool_test.go:100 (0x508c9a)
func.259: Expect(pubsub.Close()).NotTo(HaveOccurred()) …
```
=> Don't panic if list is closed and conn can't be found.

.travis.yml, Makefile, cluster.go, cluster_test.go, commands_test.go, internal/consistenthash/consistenthash.go, internal/consistenthash/consistenthash_test.go, main_test.go, multi.go, pool.go, pool_test.go, redis_test.go, ring.go, ring_test.go
I called it Ring, because client uses consistent hash ring to distribute keys.
@dim would be nice to hear you opinion.
=> Add Redis Ring.

commands.go, commands_test.go
- Added isLex boolean to zRangeByScore.
- Added if statement to zRangeByScore which checks isLex.
* If isLex is true, runs ZRANGEBYLEX rather than ZRANGEBYSCORE against the zset.
- Implemented ZRangeByLex.
- Added tests for ZRangeByLex to commands_test.go.
=> Implemented ZRangeByLex and ZRevRangeByLex with tests.

example_test.go, main_test.go, pool.go, pubsub.go, pubsub_test.go, redis_test.go
ReceiveMessage automatically reconnects to Redis on network error.
=> Add PubSub.ReceiveMessage.

command.go, parser.go
Scan command reply parsing should be much more efficient now.
=> Add readScanReply.

conn.go, conn_test.go, export_test.go, main_test.go, multi.go, pool.go, pool_test.go, pubsub.go, redis_test.go, sentinel.go
Fixes https://github.com/go-redis/redis/issues/172
=> Fix pool panic on slow connection with MaxRetries > 0.

command.go, commands.go, commands_test.go
Change-Id: Ia6144617f42629af4c022e595c444ddc6d66f1a3
=> Added binding for GEORADIUSBYMEMBER, GEODIST AND GEOHASH.

commands.go, commands_test.go
Could you take a look at my implementation for issue #182 ?
=> Implemented PFADD, PFCOUNT, PFMERGE

.travis.yml, cluster_pipeline.go, cluster_test.go, error.go, main_test.go, multi.go, multi_test.go, pipeline.go, pool.go, pool_test.go, pubsub.go, pubsub_test.go, redis.go, redis_test.go, ring.go
Fixes https://github.com/go-redis/redis/issues/185
=> multi: fix recovering from bad connection.

command.go, commands.go, commands_test.go, parser.go
Fixes https://github.com/go-redis/redis/issues/187
=> Fix GeoRadius reply parsing.

.travis.yml, Makefile, cluster_test.go, commands_test.go, example_test.go, pubsub.go, pubsub_test.go, redis.go, ring.go, ring_test.go
Fixes https://github.com/go-redis/redis/issues/191
=> Fix doc comment for PoolTimeout.

example_test.go
I've struggled a lot with BLPop until I read source code and throwed some experiments. Hope this help to somebody.
=> docs: add BLPop example

pool.go, pubsub_test.go
Replaces https://github.com/go-redis/redis/pull/199
=> Fix PubSub panic on concurrent Close.

cluster.go, pool.go
=> Fix sporadic pool timeouts with IdleTimeout != 0. Fixes #195.

commands.go
=> Added CLUSTER FORGET command

commands.go, commands_test.go
Can save []byte -> string conversion in some cases.
=> Accept interface{} values in list and set commands.

cluster.go, cluster_pipeline.go, cluster_test.go, multi.go, multi_test.go
Fixes https://github.com/go-redis/redis/issues/203
Fixes https://github.com/go-redis/redis/pull/217
=> cluster: add Watch support.

commands_test.go, multi.go, parser.go
Fixes https://github.com/go-redis/redis/issues/224
=> Improve nil reply parsing.

.travis.yml, multi.go, pool.go, pool_test.go, pubsub.go, redis.go, sentinel.go
Updates https://github.com/go-redis/redis/issues/222
@dim PTAL
=> Better rate limited message.

cluster.go, commands.go, multi.go, pool.go, pubsub.go, redis.go, ring.go, sentinel.go
This allow users of the API to override the Logger. Fix #250.
=> Declare and use a package-level Logger

command.go, parser.go
Changed in https://github.com/antirez/redis/commit/c285862621b2db70ec9152f5e081a091d49a0a45
=> Fix cluster slots parsing.

Makefile, bench_test.go, internal/pool/bench_test.go, internal/pool/pool.go
Doesn't fix https://github.com/go-redis/redis/pull/273#issuecomment-195713061 though
=> Move benchmark to relevant package. Added bench task

command_test.go, parser.go
Fixes https://github.com/go-redis/redis/issues/278
=> Fix slice grow in readN.

Makefile, cluster.go, cluster_pipeline.go, cluster_test.go, command_test.go, commands_test.go, error.go, example_test.go, internal/pool/conn.go, internal/pool/conn_list.go, internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go, internal/pool/pool_test.go, main_test.go, multi.go, multi_test.go, options.go, pipeline.go, pool_test.go, pubsub.go, pubsub_test.go, redis.go, redis_test.go, ring.go
Updates https://github.com/go-redis/redis/issues/278
=> Add race test for big vals.

cluster.go, internal/pool/pool.go
Updates https://github.com/go-redis/redis/issues/292
=> Improve comment.

cluster_pipeline.go, cluster_test.go
Updates https://github.com/go-redis/redis/issues/291
=> Add cluster pipeline test.

commands.go, example_test.go, script.go
For v4 since this is API change
=> Accept interface{} in Eval. Fixes #243.

command.go, commands.go, example_test.go, iterator.go, iterator_test.go, redis.go
Here you go, as promised in #303
=> Scan iterators (v4)

commands.go, commands_test.go
Squashed version of https://github.com/go-redis/redis/pull/313
=> Add HMSetMap.

cluster.go, cluster_test.go, example_test.go, pool_test.go, race_test.go, redis_test.go, tx.go, tx_test.go
The good thing about this API is that Tx is automatically closed.
=> Tweak transaction API.

internal/log.go, redis.go
Updates https://github.com/go-redis/redis/issues/323
=> Cleanup loggers.

parser.go, race_test.go
Updates https://github.com/go-redis/redis/issues/335
=> Make readLine more strict.

commands.go
https://github.com/go-redis/redis/issues/341
=> Feature: Export cmdable as an interface

options.go, ring.go, ring_test.go
Fixes https://github.com/go-redis/redis/issues/349
=> ring: reduce HeartbeatFrequency.

command.go, commands.go, parser.go
Added missing GEOPOS command.
But I'm not sure about part of code below, redis could produce "nil" as element of array response. If there are another solution tell me
```
// response may contain nil results
if err == Nil {
positions = append(positions, nil)
continue
}
```
=> Support geopos command

internal/pool/pool.go, internal/pool/pool_test.go
Replaces https://github.com/go-redis/redis/pull/363
=> internal/pool: fix reaper to properly close connections.

commands.go
Fixes https://github.com/go-redis/redis/issues/367
=> Fix Cmdable interface.

commands.go
Related: https://github.com/go-redis/redis/issues/367
=> Remove unexported functions from Cmdable interface

.travis.yml, internal/errors/errors.go
Fixes https://github.com/go-redis/redis/issues/370
=> Try to fix Go 1.4.

cluster.go, commands.go, redis.go, ring.go
Fixes https://github.com/go-redis/redis/issues/372#issuecomment-248756134
=> Add Pipeline to Cmdable.

cluster.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/373
=> Don't panic when cluster does not have valid nodes.

cluster.go, pipeline.go, redis.go, ring.go
Updates https://github.com/go-redis/redis/issues/399
=> Retry multiple commands more conservatively.

cluster_test.go, example_test.go, pool_test.go, race_test.go, redis_test.go, tx.go, tx_test.go
Fixes https://github.com/go-redis/redis/pull/398/files
=> Refactor Tx using Pipeline to implement Cmdable interface.

internal/proto/reader.go, race_test.go, redis_test.go
Updates https://github.com/go-redis/redis/issues/417
=> Limit allocation.

commands.go, commands_test.go, example_instrumentation_test.go, example_test.go, pipeline_test.go, redis.go, ring.go
Example when run outputs following:
```
Redis<:6379 db:0>: processed=144952 avg_dur=17µs
Redis<:6379 db:0>: processed=291016 avg_dur=17µs
Redis<:6379 db:0>: processed=436661 avg_dur=17µs
Redis<:6379 db:0>: processed=580036 avg_dur=14µs
Redis<:6379 db:0>: processed=724705 avg_dur=17µs
Redis<:6379 db:0>: processed=870215 avg_dur=17µs
```
=> Fix WrapProcess for Ring and Cluster. Add better example.

cluster.go, cluster_test.go, command.go, internal/pool/conn.go, internal/pool/pool.go, internal/pool/pool_sticky.go, main_test.go, options.go, pipeline.go, pipeline_test.go, pubsub.go, pubsub_test.go, redis.go, redis_test.go, ring.go, sentinel.go, tx.go, tx_test.go
Fixes https://github.com/go-redis/redis/issues/430
=> Set read/write timeouts more consistently.

cluster.go
=> fix cmdInfo nil pointer panic

cluster.go, cluster_test.go, tx.go
Fixes https://github.com/go-redis/redis/issues/442
=> Fix nil ptr in case when all nodes are unavailable.

cluster.go, ring.go
Fixes https://github.com/go-redis/redis/issues/446#issuecomment-267004682
=> Use first slot/shard when key is not defined.

cluster.go
When resolving node latency, each nodes is being ping a couple of times (10 right now).
In case of large cluster spread across the world initialisation can take a while as each node is ping one after the other. Doing each node in parallel will decrease the general initialisation time.
NB: Doing it against V4 right now as my projects are still using this version but I will try to push one against V5 soon.
=> Setting node latency can take a while

redis.go
Updates https://github.com/go-redis/redis/issues/459
=> Allow creating PubSub without channels.

commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/437
=> Add unlink command.

example_instrumentation_test.go
Failed test added. Works for me in v4.
=>  WrapProcess is broken in v5

commands_test.go
Updates https://github.com/go-redis/redis/issues/468
=> Add Eval test.

command.go, commands.go, iterator.go
Fixes https://github.com/go-redis/redis/pull/467
=> Remove Scanner in favor of ScanCmd.

redis.go, redis_context.go, redis_no_context.go
`client.Copy()` method which will properly set `client.cmdable.process = client.Process`
And `client.WithContext(c)` that will do the same + set context.
=> Clone and WithContext #471

commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/476
=> Add ZRemRangeByLex.

commands.go
Updates https://github.com/go-redis/redis/pull/436
=> ObjectIdleTime accepts one key.

Makefile, command.go, internal/pool/conn.go, internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go, internal/pool/pool_test.go, internal/proto/reader.go, internal/proto/reader_test.go, internal/proto/write_buffer.go, internal/proto/write_buffer_test.go, pool_test.go, pubsub.go, pubsub_test.go, redis.go, redis_test.go, sentinel.go, tx_test.go
Updates https://github.com/go-redis/redis/issues/485
=> Fix ReceiveMessage to work without any subscriptions.

commands.go, commands_test.go
Reference: https://redis.io/commands/wait
=> Added implementation for WAIT command

README.md, cluster.go, cluster_test.go, example_test.go, universal.go, universal_test.go
I've been maintaining https://github.com/bsm/multiredis for a while as it simplifies many use cases and testing scenarios. It has been really useful and I would like to include it into the main repo.
=> Added support for multi-client

universal.go
=> Expose Process on UniversalClient

pubsub.go
Fixes https://github.com/go-redis/redis/issues/500
=> Use simple PING for compatibility

cluster.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/520
=> Don't panic if cluster state is nil.

cluster.go, redis.go, ring.go
Fixes https://github.com/go-redis/redis/issues/529
=> Add ability to read client options

pubsub.go, redis.go
Fixes https://github.com/go-redis/redis/issues/550
=> Initialize PubSub connection

command.go
Remove unnecessary if and return the value directly
=> Remove unnecessary code

bench_test.go, cluster.go, cluster_test.go, commands.go, commands_test.go, example_test.go, pipeline.go, pipeline_test.go, pool_test.go, race_test.go, redis.go, redis_test.go, ring.go, ring_test.go, tx.go, tx_test.go
@vmihailenco can you take a look on it?
I'm not sure with what I did here https://github.com/felipejfc/redis/blob/6fca4d5ad05fdb809fb3ffafcb2b30c6be8b41f7/pipeline.go#L101-L107
To make possible for Pipeline to implement Cmdable thus not having to create yet another Cmdable-like interface.
This must solve  https://github.com/go-redis/redis/issues/555
Regards
=> pipeline now has its own interface "Pipeliner"

cluster.go, command.go, ring.go
Fixes https://github.com/go-redis/redis/issues/559
=> Export Cmder.Name

script.go
Fixes https://github.com/go-redis/redis/issues/566
=> Add Script.Hash

internal/errors.go, internal/internal.go, internal/internal_test.go, internal/pool/pool.go, options.go, redis.go, redis_test.go, testdata/redis.conf
Fixes #562 .
Notes:
* Made ```max number of clients reached``` a retryable error
* Backoff Max Time is configurable via config options
Please let me know if I need to adjust anything to make this PR mergable... Thanks!
=> Backoff retry 

.travis.yml, cluster.go, internal/once.go, ring.go
Closes https://github.com/go-redis/redis/pull/584
=> Vendor syncutil.Once

cluster.go, cluster_test.go, export_test.go, internal/internal.go, internal/internal_test.go, options.go, pubsub.go, pubsub_test.go, redis.go, ring.go, sentinel.go
Fixes https://github.com/go-redis/redis/issues/141
=> Add PubSub support to Cluster client

command.go, commands.go
Fixes https://github.com/go-redis/redis/issues/599
=> Add Geo commands read-only variants

pubsub.go, pubsub_test.go
Fixes https://github.com/go-redis/redis/issues/610
=> Fix PubSub.Subscribe deadlock

cluster.go, cluster_test.go, commands.go, commands_test.go, internal/error.go, pubsub_test.go
Fixes https://github.com/go-redis/redis/issues/621
=> Add ZLexCount

cluster.go, cluster_test.go, command.go, commands_test.go, export_test.go, internal/error.go, internal/proto/reader.go, internal/proto/scan.go, main_test.go, pubsub.go, redis.go, ring.go, tx.go
Updates https://github.com/go-redis/redis/issues/629
=> Rework pipeline retrying

cluster_commands.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/632
=> Add Cluster.DBSize

cluster.go, commands_test.go, internal/pool/pool.go, pool_test.go, pubsub_test.go, ring.go
This is more reliable if you want number of misses
=> Replace PoolStats.Requests with PoolStats.Misses

internal/pool/pool.go
We've been experiencing a few panics related to connection errors. Looks like storing error interfaces in `atomic.Value` isn't a good idea:
```
panic: sync/atomic: store of inconsistently typed value into Value
goroutine 1 [running]:
sync/atomic.(*Value).Store(0xc42009a0a0, 0x5fdb00, 0xc42011d540)
/home/dim/.gimme/versions/go1.9.linux.amd64/src/sync/atomic/value.go:79 +0x10d
bitbucket.org/infectious/tsdb/vendor/github.com/go-redis/redis/internal/pool.(*ConnPool).setLastDialError(0xc42009a090, 0x76d840, 0xc42011d540)
/home/dim/src/bitbucket.org/infectious/tsdb/vendor/github.com/go-redis/redis/internal/pool/pool.go:141 +0x4e
bitbucket.org/infectious/tsdb/vendor/github.com/go-redis/redis/internal/pool.(*ConnPool).NewConn(0xc42009a090, 0xc420097da0, 0xc4203f8001, 0xc4203f8000) …
```
=> Fix pool panics

pubsub.go
Fixes https://github.com/go-redis/redis/issues/657
=> Create PubSub channel once

internal/proto/scan.go, internal/util.go
Fixes https://github.com/go-redis/redis/issues/662
=> Fix slice next elem func

command.go, commands.go, commands_test.go, parser.go
I added a SMembersMap command that returns sets as map[string]struct{} as discussed in go-redis/redis#666
=> Add SMembersMap command

README.md
Just a quick [grammar fix](https://ell.stackexchange.com/a/128808) in the README.
=> Fix grammar in quickstart

example_test.go
Sorry for the noise - I missed this in #669. Same thing, different file.
=> Fix grammar in ExampleClient

commands.go, universal.go
=> Added subscription interfaces to universal client

commands.go, redis.go
Fixes https://github.com/go-redis/redis/issues/655
=> Mention redis.Nil

.travis.yml, cluster.go, cluster_test.go, command.go, internal/hashtag/hashtag.go, ring.go
Fixes https://github.com/go-redis/redis/issues/687
=> Pick random node when command does not have keys

cluster.go
Fixes https://github.com/go-redis/redis/issues/695
=> Retry if node is closed; close nodes with delay

cluster.go, cluster_test.go, commands_test.go
Updates https://github.com/go-redis/redis/issues/706
=> Update cluster node latency asynchronously

cluster_test.go, commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/708
=> Add SortStore and fix Sort signature

commands.go, commands_test.go
See redis document.
* Touch: https://redis.io/commands/touch
* SwapDB: https://redis.io/commands/swapdb
=> Add two new commands: Touch and SwapDB

cluster.go, cluster_test.go, internal/error.go, internal/singleflight/singleflight.go
Fixes https://github.com/go-redis/redis/issues/706
=> Rework retrying

cluster_test.go, command.go, commands.go, commands_test.go, internal/error.go, internal/proto/reader.go, internal/proto/scan.go, internal/util.go, internal/util/safe.go, internal/util/strconv.go, internal/util/unsafe.go, parser.go, redis.go, tx.go
Fixes https://github.com/go-redis/redis/issues/715
=> Fix proto.RedisError in slices

cluster.go, redis_test.go
Fixes https://github.com/go-redis/redis/issues/717
=> Use fresh cluster state after sleeping

commands.go, commands_test.go
This commit adds support for config rewrite as documented in
https://redis.io/commands/config-rewrite .
=> Impement Config Rewrite command

Makefile, cluster.go
Fixes https://github.com/go-redis/redis/issues/731
=> Fix build on 32bit arch

cluster_test.go, main_test.go, race_test.go
Closes https://github.com/go-redis/redis/issues/697
=> Add race test for BLPop

redis.go, redis_test.go
Fixes https://github.com/go-redis/redis/issues/741
=> Fix WithContext followed by WrapProcess

universal.go
=> Add Watch func to UniversalClient interface

cluster.go
Fixes https://github.com/go-redis/redis/issues/753
=> cluster: retry same node on retryable error

cluster.go
Closes https://github.com/go-redis/redis/pull/763
=> cluster: reload state for ForEach functions and every 1 minute

cluster.go
Fixes https://github.com/go-redis/redis/issues/771
=> cluster: fix origin addr check

sentinel.go
Fixes https://github.com/go-redis/redis/issues/777
=> Export SentinelClient

internal/error.go
Fixes https://github.com/go-redis/redis/issues/790
=> Close read-only connections

command.go, commands.go, commands_test.go
This is based on https://github.com/go-redis/redis/pull/670 with some simplifications and API changes. I've chosen https://github.com/go-redis/redis/pull/670, because it came first and is much smaller compared to https://github.com/go-redis/redis/pull/779. The plan is to merge this PR first and continue in https://github.com/go-redis/redis/pull/779 to add missing APIs.
@nicktylah @kassiansun please take a look
=> Add basic redis streams support

cluster.go, cluster_test.go, example_test.go, main_test.go
Fixes https://github.com/go-redis/redis/issues/433
=> cluster: add manual setup

cluster.go, commands.go, pubsub.go, redis.go
Fixes https://github.com/go-redis/redis/issues/808#issuecomment-405202883
=> Conn timeout should be higher than read timeout

commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/816
=> Add MemoryUsage

ring.go
We currently use redis ring with 10 nodes, however we encounter uneven load between different nodes, which can be as high as 40%. After some experiment, we found that the default configuration of consistent has used in ring, 100 nreplicas and crc32 hash function is not optimal for our use case. In our case, use 1000 nreplicas and xxhash hash function provide almost even distribution of keys between nodes. This pull request implements the functionality to set nreplicas and hash function in RingOptions to customize the behavior of consistent hash in ring.
=> Hash function and nreplicas in consistent hash can be set in RingOptions

cluster.go, cluster_test.go, export_test.go, internal/hashtag/hashtag.go, main_test.go, ring.go
Fixes https://github.com/go-redis/redis/issues/803
=> cluster: optimize newClusterState

cluster.go, command.go, internal/pool/conn.go, internal/pool/pool.go, internal/proto/bufio_reader.go, internal/proto/reader.go, internal/proto/reader_test.go, internal/proto/write_buffer.go, internal/proto/write_buffer_test.go, pubsub.go, pubsub_test.go
Updates https://github.com/go-redis/redis/issues/832
=> Use single read and write buffer where possible

internal/pool/conn.go, internal/pool/pool.go, internal/pool/pool_test.go, options.go
Replaces https://github.com/go-redis/redis/pull/778
=> Add MinIdleConns

cluster.go
=> execute commans concurrently on each cluster node in method `defaultProcessPipeline`

commands.go, redis.go
Fixes https://github.com/go-redis/redis/issues/863
=> Set cmd timeout when Block >= 0

cluster.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/869
=> Don't enable ReadOnly in custom cluster mode

example_test.go, pubsub.go, sentinel.go
Updates https://github.com/go-redis/redis/issues/873
=> Use PubSub.Channel to not burn CPU on errors

options.go, options_test.go
Add comment to the ReadTimeout option and test for it.
=> Add test for read timeout option

sentinel.go
Fixes https://github.com/go-redis/redis/issues/881
=> Copy TLSConfig to SentinelClient options

sentinel.go
Fixes https://github.com/go-redis/redis/issues/888
=> Fix closing nil sentinel

sentinel.go
Currently, the pubsub connection is aggressively disconnected when we close the upstream client which causes it to log something like:
redis: 2018/11/09 09:10:07 pubsub.go:151: redis: discarding bad PubSub connection: read tcp 127.0.0.1:61025->127.0.0.1:26378: use of closed network connection
This change simply cleans up the connection on close.  
We create new redis servers and connections for each set of independent tests and the logs were getting spammy.
=> Cleanup sentinel pubsub on close

commands.go, commands_test.go
This PR adds support for the stream command XDEL, which seems to be missing.
=> Add support for XDEL

cluster.go, cluster_test.go, export_test.go
Fixes https://github.com/go-redis/redis/issues/912
=> Remove Redis Cluster state check

commands.go, commands_test.go
Closes https://github.com/go-redis/redis/issues/920
=> Add Client Id

redis.go
Fixes https://github.com/go-redis/redis/pull/884#issuecomment-446496137
=> Remove limiter copy

cluster.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/918
=> clusterStateHolder.Get should load a state when there is none

commands.go, commands_test.go
https://github.com/go-redis/redis/issues/921
=> Add Client Unblock

cluster.go
Replaces https://github.com/go-redis/redis/pull/931/files
=> Retry cluster pipeline read commands

example_test.go
Includes some comments on the transaction steps.
=> FIX: WATCH example stack protection (with retry count)

cluster.go
Updates https://github.com/go-redis/redis/issues/945
=> Reload cluster state almost on any error

pipeline.go, pipeline_test.go
Fixes https://github.com/go-redis/redis/issues/962
=> Support custom command in pipeline

cluster.go
Replaces https://github.com/go-redis/redis/pull/950
=> Don't remember cluster node for the PubSub

pipeline.go
Fixes https://github.com/go-redis/redis/issues/962#issuecomment-462442503
=> Add Pipeliner.Do

commands.go
Closes https://github.com/go-redis/redis/pull/969
=> Add Streams comment

sentinel.go
=> Add the failover sentinel command

cluster.go, internal/error.go
Fixes https://github.com/go-redis/redis/issues/977
=> Retry master node on readonly errors. Fixes #977

sentinel.go
Sorry, I should have open only one PR instead of three separate PRs...
Here I add two sentinel commands I needed: `Master` and `FlushConfig`
=> Add a couple of sentinel commands

cluster.go, cluster_test.go
Fixes https://github.com/go-redis/redis/issues/984
=> Use random node when there are no channels

pubsub.go, pubsub_test.go
Fixes https://github.com/go-redis/redis/issues/887
Fixes https://github.com/go-redis/redis/issues/949
Closes https://github.com/go-redis/redis/pull/991
=> pubsub: drop a message when the channel is full

internal/pool/conn.go, internal/pool/export_test.go, internal/pool/pool.go, internal/pool/pool_test.go, redis.go
Fixes https://github.com/go-redis/redis/issues/995
=> Fix MinIdleConns and MaxConnAge

command.go, command_test.go
Closes https://github.com/go-redis/redis/pull/1008
=> Add Float32 helper

command.go, redis.go, sentinel.go
* Rewrite if-else chain as a switch.
* Rewrite switch statement with only one case as if.
* Remove always true condition.
* Simplify some functions.
=> Some code improvements

ring.go, ring_test.go
Adding support for `Watch` method in `Ring` (this will make `Ring` fulfill `UniversalClient` interface)
=> Ring Watch

cluster.go, go.mod, options.go, redis_test.go, sentinel.go, universal.go
Fixes https://github.com/go-redis/redis/issues/1027
=> Pass network and addr to dialer

Makefile, command.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/1026
=> Handle -1 in DurationCmd

cluster.go, internal/pool/bench_test.go, internal/pool/main_test.go, internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go, internal/pool/pool_test.go, options.go, pool_test.go, redis.go, redis_test.go, ring.go, sentinel.go, tx_test.go, universal.go
Updates https://github.com/go-redis/redis/issues/1025#issuecomment-498576942
=> Pass context to Dialer

cluster.go, internal/pool/conn.go, pubsub.go, redis.go, ring.go
Updates https://github.com/go-redis/redis/issues/582
=> Use Context.Deadline to set net.Conn deadline

internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go
Fixes https://github.com/go-redis/redis/issues/582
=> Check context.Done while waiting for a connection

cluster.go, internal/pool/conn.go, internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go, redis.go, sentinel.go
Closes https://github.com/go-redis/redis/issues/1049
=> internal/pool: use min nonzero deadline

internal/proto/reader.go
Fixes https://github.com/go-redis/redis/issues/1042
=> Don't panic if multi bulk parser is nil

internal/pool/pool.go
Closes https://github.com/go-redis/redis/pull/1055/files
=> Inc StaleConns in ReapStaleConns

command.go, commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/1036
=> Add basic BITFIELD support

cluster.go
Fixes https://github.com/go-redis/redis/issues/1069
=> Fix cmdsInfo to create node

cluster.go, cluster_test.go, internal/pool/bench_test.go, internal/pool/pool.go, internal/pool/pool_test.go, pipeline.go, pool_test.go, redis.go, redis_test.go, ring.go, ring_test.go, sentinel.go, tx.go, tx_test.go
Fixes https://github.com/go-redis/redis/pull/1040#issuecomment-508208646
=> Fix WithContext and add tests

CHANGELOG.md, pubsub.go
Closes https://github.com/go-redis/redis/pull/1074
=> Change PubSub.Channel

cluster.go, ring.go
Fixes https://github.com/go-redis/redis/issues/979
=> Implement TxPipeline for Ring

cluster.go, internal/error.go, internal/util.go, redis.go, ring.go, tx.go
Fixes https://github.com/go-redis/redis/issues/1100
Closes https://github.com/go-redis/redis/issues/1107
=> Cancel sleep when context is cancelled

cluster.go, error.go, example_test.go, internal/pool/pool_single.go, pubsub.go, redis.go, ring.go
Updates https://github.com/go-redis/redis/issues/1113
=> Add proper SingleConnPool implementation

cluster.go, command.go, redis.go, ring.go
Fixes https://github.com/go-redis/redis/issues/1099
=> Add withConn and set cmd errors more consistently

command.go, commands.go, commands_test.go, internal/pool/pool.go, internal/proto/reader.go
Fixes https://github.com/go-redis/redis/issues/1083
=> Add writing version of GeoRadius commands

go.mod, internal/pool/bench_test.go, internal/pool/pool.go, internal/pool/pool_single.go, internal/pool/pool_sticky.go, internal/pool/pool_test.go, internal/util.go, redis.go
Updates https://github.com/go-redis/redis/issues/1113
=> Port SingleConnPool fix to v6

cluster.go, race_test.go, redis.go, ring.go, sentinel.go, tx.go
Fixes https://github.com/go-redis/redis/issues/1136
=> Fix WithContext race

sentinel.go
SentinelClient is not closed due to race condition causing leak of 3 goroutines. Reproduced on high load ( thousands rps)
=> Sentinel goroutine leak fixed

sentinel.go
such as https://godoc.org/golang.org/x/net/proxy#PerHost DialContext
=> sentinel uses configured Dialer

commands.go
=> fix:Set operation claims insufficient memory (#1203)

.travis.yml, Makefile, commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/1216
=> Use HSET for HMSet

commands.go, commands_test.go
Fixes https://github.com/go-redis/redis/issues/1218
=> Fix HMSet args size

CHANGELOG.md, cluster_test.go, example_test.go, race_test.go, redis_test.go, ring_test.go, tx.go, tx_test.go
Fixes https://github.com/go-redis/redis/issues/1233#issuecomment-573107328
=> Change Tx.Pipeline and Tx.TxPipeline meaning

redis.go, redis_test.go
Fixes https://github.com/go-redis/redis/issues/1214
=> Set an error returned from the hook on the Cmd

options.go, redis.go, redis_test.go, sentinel.go
Closes https://github.com/go-redis/redis/issues/1236
=> Add WithTimeout

cluster.go, cluster_commands.go, command.go, command_test.go, commands.go, redis.go, result.go, ring.go
=> Exported the setErr function as public

cluster.go, redis.go, ring.go, tx.go
Fixes https://github.com/go-redis/redis/issues/1258
=> Unexport Clone and Lock from embedded hooks

bench_test.go, cluster.go, cluster_test.go, command.go, example_test.go, main_test.go, race_test.go, redis.go, ring.go, ring_test.go, tx.go
Fixes https://github.com/go-redis/redis/issues/1223#issuecomment-586185820
=> Don't allocate tmp slice in txPipelineWriteMulti

commands_test.go
Fixes https://github.com/go-redis/redis/issues/1268
=> Fix tests on 32bit arches

result.go
Needed this function for some unit tests
=> add NewTimeCmdResult to allow unit testing with TimeCmd

cluster.go, commands.go, options.go, options_test.go, redis.go, ring.go, sentinel.go, universal.go
fixes #1322 by adding `AuthACL` as a command, and by properly parsing the url with the user info
=> [add] Add support for ACL new

internal/log.go, redis.go
=> Use an interface for logging

README.md
=> [DOC] Add ctx declaration in readme

go.mod, go.sum, ring.go
diff
https://github.com/cespare/xxhash/compare/v1.1.0...v2.1.1
=> upgrade xxhash to v2

command.go
See https://github.com/redis/redis/issues/7493
We have to include a special handling for the memory usage command
=> handle memory usage command arguments

cluster.go, commands.go, internal/instruments.go, internal/log.go, internal/pool/pool.go, pubsub.go, ring.go, sentinel.go
=> Log with context to associate all log by traceID

cluster.go
Updates https://github.com/go-redis/redis/issues/1317
=> Try 3 random addrs to load commands

options.go
This is hugely useful for debugging subtly broken setups where one of the addresses turns out to be wrong.
=> Trace dialer targets in the relevant spans

sentinel.go
Fixes #1447
Signed-off-by: Dmitry Shmulevich <dmitry.shmulevich@sysdig.com>
=> Properly pass username/password in Sentinel

universal.go
Signed-off-by: Dmitry Shmulevich <dmitry.shmulevich@sysdig.com>
=> add Sentinel password to UniversalOptions

main_test.go, sentinel_test.go, universal_test.go
Signed-off-by: Dmitry Shmulevich <dmitry.shmulevich@sysdig.com>
=> use 3 sentinel instances in unit testing

redis.go
Fixes https://github.com/go-redis/redis/issues/1476
=> Change hooks to be LIFO

cluster.go, cluster_test.go
Updates https://github.com/go-redis/redis/issues/1438
=> Periodically update Cluster node latency

pubsub.go
Fixes https://github.com/go-redis/redis/issues/1492
=> Do not use retry backoff in PubSub

command.go, commands.go
This adds support for the `XINFO STREAM` command.
=> Add XINFO STREAM

options.go, options_test.go
There is only one way if you choose to connect to redis by url string: connect by tcp socket.
This PR offers the way to connect to unix socket using url string as well.
=> Add unix socket connection by url stirng.

internal/pool/conn.go, internal/util.go, options.go, redis.go
Closes https://github.com/go-redis/redis/pull/1512
=> otel: add RemoteAddr

internal/internal.go
Fixes https://github.com/go-redis/redis/issues/1548
=> Guard against overflow in retry

.github/workflows/go.yml, commands.go, commands_test.go
Because I started using this library recently, I'm not sure if the functions I've created align with the rest of the library's API.
I've decided to create two functions `LPos` and `LPosCount` that both accept Maxlen as the last parameter, I did not create any structs because it didn't seem necessary.
It did cross my mind to create 4 Commands (`LPos`, `LPosMaxlen`, `LPosCount` and `LPosCountMaxlen`) because maxlen is only used in very special cases.
=> Add LPOS command

redis.go
Fixes https://github.com/go-redis/redis/pull/1573
@roy2220 PTAL
=> Wait for the goroutine to finish

README.md
Hi maintainers.
I am new to golang. And I tried to figure out how to run the test for go-redis project. It seems there is no document yet for this. So I would like to add few lines to describe how I run the test suite.
Please correct me if it's wrong. Thanks for your patience.
=> Added test setup document in README.md

cluster.go, cluster_test.go, internal/pool/pool.go
Fixes https://github.com/go-redis/redis/issues/1586
=> Fix Tx pipeline hook

cluster.go
Updates https://github.com/go-redis/redis/issues/1614
=> Fix ReadOnly option in ClusterClient

cluster.go
Fixes https://github.com/go-redis/redis/issues/1682
Closes https://github.com/go-redis/redis/pull/1683
=> Don't accept context in lazy reload

commands.go
hgetall return map[string]string ,but hmset do not support map[string]string
=> hmset support map[string]string

commands.go, commands_test.go
Add the LMove command as per issue 
https://github.com/go-redis/redis/issues/1721
=> add LMove with tests

.github/workflows/build.yml, .github/workflows/golangci-lint.yml, command.go, commands.go, commands_test.go
sync master
workflows add v9(push/golangci-lint)
=> sync master to v9

commands.go, commands_test.go
=> Add the count option to the rpop command(fix #1813)

Makefile, commands_test.go
=> Upgrade redis-server version

CHANGELOG.md
It is not a full list of changes, but it should be a good start
=> Update changelog for v9

.github/workflows/release.yml, RELEASING.md, scripts/release.sh, scripts/tag.sh
I've tested the shell scripts on https://github.com/uptrace/bun and they seem to work fine. But I am not sure if release.yml is working properly - we will have to figure it out the hard way :)
=> Automate release process

redis.go
* Fixed https://github.com/go-redis/redis/issues/1885.
=> empty hooks.withContext removed

command.go
=> fix(#1943): XInfoConsumer.Idle should be time.Duration instead of int64

Makefile, README.md, command.go, commands_test.go, export_test.go, internal/proto/reader.go, main_test.go, redis.go, sentinel.go
Fixes https://github.com/go-redis/redis/issues/2106
Fixes https://github.com/go-redis/redis/issues/2085
Fixes https://github.com/go-redis/redis/issues/2082
Fixes https://github.com/go-redis/redis/issues/2080
=> feat: upgrade to Redis 7

cluster.go
It is possible that a ping command might fail very quickly due to an
immediate connection refused message or some other server failure condition.
In this case, the derived latency is not reliable and should not be used
to compare this node to other nodes in the cluster.
This change will only count successful Ping commands in the average latency
and in the case of no successful Pings, set the latency to an arbitrarily
high value to make this node have the least priority when routing by latency.
=> Disregard failed Pings in updateLatency() for cluster nodes

ring.go
Hi!
We continue to investigate various problems with `Ring` which arise from our case, briefly described in #2126.
This time it is massive goroutines leaks of Heartbeat goroutines. The reason is that there is no way to exit the ticker `range channel` loop: 
https://github.com/go-redis/redis/blob/e061db8c13fd6b5e007d73370873026e360719de/ring.go#L313-L334
Simple program to demonstrate the problem:
```go
package main
import (
"context"
"fmt"
"log"
"net/http"
_ "net/http/pprof"
"runtime"
"github.com/go-redis/redis/v9"
)
func main() {
ctx := context.Background()
opts := &redis.RingOptions{
Addrs: map[string]string{
"shard0": ":6379",
},
}
for i := 0; i < 1000; i++ {
rdb := redis.NewRing(opts)
rdb.Ping(ctx)
rdb.Close()
}
// Let's check how many Goroutines we have now …
```
=> fix: provide a signal channel to end heartbeat goroutine

command.go
=> feat: add some missing SetVal methods

iterator.go
It's not safe to concurrently use an iterator even with a mutex.
Fixes https://github.com/go-redis/redis/issues/2165.
=> fix: remove iterator mutex as it's not needed

cluster.go, cluster_test.go, commands.go, pubsub.go, pubsub_test.go, redis.go, ring.go, universal.go
Closes #2115 
Sharded pub/sub ref: https://redis.io/docs/reference/cluster-spec/#publishsubscribe
=> feat(pubsub): support sharded pub/sub

sentinel.go
Hi! My app's logs are full of errors that look like this:
```
redis: 2022/06/18 01:21:35 sentinel.go:587: sentinel: GetMasterAddrByName name="gprd-redis" failed: context canceled
redis: 2022/06/18 01:21:35 sentinel.go:587: sentinel: GetMasterAddrByName name="gprd-redis" failed: context canceled
redis: 2022/06/18 01:21:35 sentinel.go:587: sentinel: GetMasterAddrByName name="gprd-redis" failed: context canceled
redis: 2022/06/18 01:21:35 sentinel.go:587: sentinel: GetMasterAddrByName name="gprd-redis" failed: context canceled
<my app's message>: redis: all sentinels specified in configuration are unreachable
```
Almost always there are several identical log lines with the same timestamp - one per configured sentinel. I looked at the code and noticed that when context is done, the code keep …
=> Return early when context signals done

commands.go, ring.go
Fix #2230
See https://github.com/go-redis/redis/issues/2177#issuecomment-1268933030
=> fix(pubsub): fix break introduced by #2177

redis.go
Fix [issue 2070](https://github.com/go-redis/redis/issues/2070)
=> fix retryTimeout in baseClient _process

redis.go
Fixes https://github.com/go-redis/redis/issues/2225
=> fix: retry dial errors from pipelines

pubsub.go
Fixes https://github.com/go-redis/redis/issues/2248
=> fix: reset pubsub state when unsubscribing from all channels

cluster.go
Fixes https://github.com/go-redis/redis/issues/2274
=> Read in the route_randomly parameter correctly in cluster mode

with_conn_test.go
Adds tests to cover the behaviour witnessed in #2272
=> Add withConn tests

redis.go, redis_test.go
Fixes https://github.com/go-redis/redis/issues/2293
=> fix: wrap cmds in Conn.TxPipeline

Makefile
Signed-off-by: Sylvain Rabot <sylvain@abstraction.fr>
=> Upgrade redis version for tests

iterator.go
The mutex was removed in v9 in #2184 as the iterator cannot be used concurrently so I think we should also drop it in v8. Assuming v8 is still supported as it is mentioned in the installation section of the readme file
=> fix(iterator): remove unnecessary mutex

cluster.go, cluster_commands.go, redis.go, redis_test.go, ring.go, sentinel.go, tx.go
=> feat: hook mode changed to FIFO

CHANGELOG.md, pipeline.go, race_test.go
Fixes https://github.com/go-redis/redis/discussions/2351
=> fix: remove mutex from pipeline

cluster.go, redis.go
In any event...we should release Conn.
=> fix(conn): releaseConn should be executed correctly

commands.go, commands_test.go
=> Expiretime and PExpireTime

internal/pool/pool.go, internal/pool/pool_test.go
=> fix: limit the number of connections created

commands.go, commands_test.go
=> Add support for BZMPOP

commands.go
=> fix(appendArg): appendArg case special type

cluster_test.go, commands.go
=> Add support for CLUSTER MYSHARDID command

cluster.go, cluster_test.go
=> feat: add field protocol to setupClusterQueryParams

options.go, osscluster.go, ring.go, sentinel.go, universal.go
=> fix missing fields in different Options

bitmap_commands.go, commands_test.go
=> Add BITFIELD_RO Command

example/del-keys-without-ttl/go.mod, example/hll/go.mod, example/lua-scripting/go.mod, example/otel/go.mod, example/redis-bloom/go.mod, example/scan-struct/go.mod, extra/rediscensus/go.mod, extra/rediscmd/go.mod, extra/redisprometheus/go.mod, go.mod, version.go
- Retract versions 9.5.3 and 9.5.4
- bump version to 9.6.1
=> cp retracts and bump version to 9.6.1

doctests/string_example_test.go
Go implementation of the code examples in the [string datatype page](https://redis.io/docs/latest/develop/data-types/strings/).
=> DOC-4213 string code examples

doctests/tdigest_tutorial_test.go
Go versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/probabilistic/t-digest/).
=> DOC-4241 added t-digest examples

doctests/bitmap_tutorial_test.go
Go versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/bitmaps/).
=> DOC-4234 added bitmap examples

doctests/bf_tutorial_test.go
Go version of the example in [this page](https://redis.io/docs/latest/develop/data-types/probabilistic/bloom-filter/).
=> DOC-4237 added Bloom filter examples

doctests/geo_tutorial_test.go
Go versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/geospatial/).
=> DOC-4233 added geospatial examples

json.go, json_test.go
* Support ReJSON resp 2 && Test ReJSON against RESP 2 and 3 && Add complex search and json test
* Remove comments
* Remove unnecessary changes
=> Backport #3146 to 9.7

probabilistic.go, probabilistic_test.go
Support the following modules with RESP 2 protocol:
* Bloom
* Cuckoo
* CMS
* TopK
* T-Digest
=> Support Probabilistic commands with RESP 2 protocol

example_test.go, sentinel.go, sentinel_test.go
close #3091 
and fix 2 warnings in file `example_test.go`
=> feat: add ParseFailoverURL

internal/pool/pool_test.go
This PR adds a simple test to exercise the error path for encountering a timeout while obtaining a connection from the pool.
I wrote this in order to exercise the logic path used by #3380.
=> Unit test for connection pool acqusition timeout

ring.go
=> fix: check if the shard exists to avoid returning nil

internal/pool/pool.go
feat: optimize connection pool waitTurn
=> feat: optimize connection pool waitTurn

pipeline_test.go, redis.go
=> fix: pipeline repeatedly sets the error
