- .travis.yml
- command_test.go
- commands_test.go
- pool.go
- pool_test.go
- redis.go
- sentinel.go
Before:
```
$ go test ./... -run=NONE -bench=Pool -benchmem -cpu=1,2,4,8 -benchtime=2s
BenchmarkPool   10000000         293 ns/op         0 B/op        0 allocs/op
BenchmarkPool-2  3000000        1127 ns/op         0 B/op        0 allocs/op
BenchmarkPool-4  2000000        1187 ns/op         0 B/op        0 allocs/op
BenchmarkPool-8  2000000        1459 ns/op         0 B/op        0 allocs/op
```
After:
```
$ go test ./... -run=NONE -bench=Pool -benchmem -cpu=1,2,4,8 -benchtime=2s
BenchmarkPool   10000000         330 ns/op         0 B/op        0 allocs/op
BenchmarkPool-2 10000000         288 ns/op         0 B/op        0 allocs/op
BenchmarkPool-4 10000000         401 ns/op         0 B/op        0 allocs/op
BenchmarkPool-8 10000000         403 ns/op         0 B/op        0 allocs/op
```
> Faster, lock-free pool

- cluster.go
- pool.go
- pool_test.go
- redis.go
- redis_test.go
Fixes https://github.com/go-redis/redis/issues/88
@dim PTAL.
I also changed default `PoolTimeout` because 5 seconds it too much for Redis and usually indicates that you have to increase pool size.
> Fix pool waiting for connection that was removed.

- pool.go
- pool_test.go
- redis.go
We have noticed that `Password` and `DB` settings are not correctly applied to connections being created as part of `pool.Put`, here's a proposed solution. PTAL
> Ensure all new connections are initialised

- cluster.go
I think there no need to reset clients, because we have connection reaper that will close connections and associated resources if client is idle. @dim ?
> cluster: don't reset clients on MOVED.

- cluster.go
- cluster_client_test.go
@dim please review
Also do you any plans how to release v3 with latest API changes and Cluster client?
> Implement Close and fix reaper goroutine leak.

- conn.go
- pool.go
- pool_test.go
- redis.go
- redis_test.go
- sentinel.go
This is very useful when you want application to exit gracefully. Existing `BenchmarkPool` numbers are not changed.
Pool was refactored a bit since I want to reuse it in https://github.com/go-pg/pg/pull/52
/cc @dim
> Fix pool to close all connections when client is closed.

- cluster.go
- cluster_client_test.go
- cluster_pipeline.go
- cluster_test.go
Since this is Go client we can use goroutine to reload slots info in background.
@dim ptal
> Reload slots in background goroutine.

- cluster.go
- cluster_test.go
This check is much stricter since it verifies that node at least knows how to handle `CLUSTER INFO` command.
> cluster: user ClusterInfo instead of Ping to find live node.

- multi.go
Remove comment since there are no use cases when `Multi` can be used from different goroutines. Should help with https://github.com/go-redis/redis/issues/111
> multi: remove confusing comment.

- cluster.go
- cluster_pipeline.go
/cc @dim 
See comment for details.
> cluster: release reloading with delay.

- redis_test.go
```
PASS
BenchmarkRedisSet	   30000	     42661 ns/op	   10666 B/op	       7 allocs/op
BenchmarkRedisSetBytes	   30000	     47951 ns/op	   21163 B/op	       8 allocs/op
```
> Add BenchmarkRedisSetBytes.

- command.go
- command_test.go
- commands.go
- commands_test.go
- conn.go
- multi.go
- parser.go
- parser_test.go
- pubsub.go
- redis_test.go
Should make client a little bit more convenient to use. @dim?
Fixes https://github.com/go-redis/redis/issues/121. Before
```
BenchmarkRedisBytes	   10000	    120101 ns/op	   52809 B/op	      16 allocs/op
BenchmarkRedisSet	   30000	     45606 ns/op	   10666 B/op	       7 allocs/op
```
After
```
BenchmarkRedisBytes	   10000	    108434 ns/op	   32022 B/op	      21 allocs/op
BenchmarkRedisSet	   30000	     46389 ns/op	   10762 B/op	      10 allocs/op
```
> Allow setting and scaning interface{} values.

- command.go
- parser.go
- unsafe.go
Benchmark
```
benchmark                       old ns/op     new ns/op     delta
BenchmarkRedisSetGet64Bytes     103732        100645        -2.98%
BenchmarkRedisSetGet1KB         104926        101539        -3.23%
BenchmarkRedisSetGet10KB        107164        102861        -4.02%
BenchmarkRedisSetGet1MB         5206102       3871532       -25.63%
benchmark                       old allocs     new allocs     delta
BenchmarkRedisSetGet64Bytes     16             15             -6.25%
BenchmarkRedisSetGet1KB         16             15             -6.25%
BenchmarkRedisSetGet10KB        16             15             -6.25%
BenchmarkRedisSetGet1MB         17             16             -5.88%
benchmark                       old bytes     new bytes     delta
BenchmarkRedisSetGet64Bytes     720 …
```
> Use unsafe for bytes->string conversion.

- sentinel.go
To follow on https://github.com/go-redis/redis/issues/148, my use case does'nt allow me to make use of redis cluster, so I make this small PR to fix my issue.
> Add MaxRetries to FailoverOptions

- unsafe.go
Hopefully this will fix
```
runtime: bad pointer in frame gopkg.in/redis%2ev3.(*BoolCmd).parseReply at 0xc840b9ec68: 0x6
fatal error: invalid stack pointer
runtime stack:
runtime.throw(0xbe16b0, 0x15)
/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0x7f92b2d288c0 sp=0x7f92b2d288a8
runtime.adjustpointers(0xc840b9ec08, 0x7f92b2d28a38, 0x7f92b2d28c28, 0xd8d130)
/usr/local/go/src/runtime/stack1.go:438 +0x2d4 fp=0x7f92b2d289b8 sp=0x7f92b2d288c0
runtime.adjustframe(0x7f92b2d28b48, 0x7f92b2d28c28, 0x1)
/usr/local/go/src/runtime/stack1.go:505 +0x1b5 fp=0x7f92b2d28a70 sp=0x7f92b2d289b8
runtime.gentraceback(0x412e40, 0xc840b9ebb8, 0x0, 0xc8202adc80, 0x0, 0x0, 0x7fffffff, 0xc980e0, 0x7f92b2d28c28, 0x0, ...)
```
> Disable unsafe.

- command.go
- commands.go
- commands_test.go
`ZADD key XX INCR CH score member` is not supported, because CH modifier seems to be ignored.
> Add ZADD modifiers.

- .travis.yml
- cluster_pipeline.go
- command.go
- conn.go
- multi.go
- parser.go
- parser_test.go
- pipeline.go
- pool.go
- pubsub.go
- redis.go
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkParseReplyStatus-4       104           106           +1.92%
BenchmarkParseReplyInt-4          139           142           +2.16%
BenchmarkParseReplyError-4        202           208           +2.97%
BenchmarkParseReplyString-4       180           202           +12.22%
BenchmarkParseReplySlice-4        889           949           +6.75%
BenchmarkAppendArgs-4             228           228           +0.00%
BenchmarkRedisClusterPing-4       11370         11477         +0.94%
BenchmarkPool-4                   215           213           -0.93%
BenchmarkRedisPing-4              7073          6933          -1.98%
BenchmarkRedisSet-4               20163         19978         -0.92%
BenchmarkRedisGetNil-4 …
```
> Get rid of custom bufio package.

- unsafe.go
Reverts https://github.com/go-redis/redis/pull/157
```
benchmark                         old ns/op     new ns/op     delta
BenchmarkParseReplyStatus-4       108           105           -2.78%
BenchmarkParseReplyInt-4          148           104           -29.73%
BenchmarkParseReplyError-4        211           211           +0.00%
BenchmarkParseReplyString-4       206           163           -20.87%
BenchmarkParseReplySlice-4        962           825           -14.24%
BenchmarkAppendArgs-4             234           234           +0.00%
BenchmarkRedisClusterPing-4       11694         11125         -4.87%
BenchmarkPool-4                   198           168           -15.15%
BenchmarkRedisPing-4              7222          7349          +1.76%
BenchmarkRedisSet-4               19931 …
```
> Enable unsafe.

- commands.go
- commands_test.go
Allows setting and getting the client connection name.
http://redis.io/commands/client-setname
http://redis.io/commands/client-getname
> Implement SetName and GetName

- commands.go
- commands_test.go
Follow-up for https://github.com/go-redis/redis/pull/178. I could add something like `client.Conn()` that returns `*redis.Client` that operates only on 1 connection, but I think it will bring more confusion than it can possibly solve.
> Fix names and add comments.

- commands.go
- commands_test.go
From http://redis.io/commands/pfcount:
> When called with multiple keys, returns the approximated cardinality of the union of the HyperLogLogs passed, by internally merging the HyperLogLogs stored at the provided keys into a temporary HyperLogLog.
> Support multiple keys for the PFCOUNT command

- pubsub.go
Noticed that when the connection got interrupted, my PSUBSCRIBE pubsub connection had turned into a SUBSCRIBE pubsub connection. I believe this fixes it.
> Bugfix: pubsub/psubscribe should register a pattern rather than channel

- pool.go
This is backwards incompatible, but fixes real bug.
Workaround for https://golang.org/src/sync/atomic/doc.go?s=1207:1656#L36
> Use uint32 because uint64 requires manual alignment on 386 arch. Fixes #256.

- commands.go
- pipeline.go
- redis.go
Minor but nevertheless:
* the `SetXX` method was only on `Client`, not on `commandable`
* some methods we exposed on the element and not the pointer: 
* https://godoc.org/gopkg.in/redis.v3#Client.Close
* https://godoc.org/gopkg.in/redis.v3#Client.String 
* https://godoc.org/gopkg.in/redis.v3#Client.ZRevRangeByLex
> Correct method accessors

- cluster_pipeline.go
- command.go
- commands_test.go
- error.go
- export_test.go
- main_test.go
- multi.go
- pipeline.go
- pool.go
- pool_test.go
- pubsub.go
- pubsub_test.go
- redis.go
- ring.go
- sentinel.go
WIth this PR go-redis closes connection on network timeout error except 2 cases:
- PubSub.ReceiveTimeout()
- Migrate, BLPop, BRPop, BRPopLPush when they are used with timeout > 0
But I still have to write tests...
Fixes https://github.com/go-redis/redis/issues/262 and https://github.com/go-redis/redis/issues/267
/cc @dim @FZambia
> Close connection on network timeout.

- bench_test.go
- internal/pool/conn.go
- internal/pool/conn_list.go
- internal/pool/pool.go
- internal/pool/pool_single.go
- internal/pool/pool_sticky.go
- multi_test.go
- options.go
- pool_test.go
- pubsub_test.go
- redis.go
- redis_test.go
- sentinel.go
```
benchmark                             old ns/op     new ns/op     delta
BenchmarkPoolGetPut10Conns-4          257           209           -18.68%
BenchmarkPoolGetPut100Conns-4         267           215           -19.48%
BenchmarkPoolGetPut1000Conns-4        242           236           -2.48%
BenchmarkPoolGetRemove10Conns-4       5559          319           -94.26%
BenchmarkPoolGetRemove100Conns-4      5751          294           -94.89%
BenchmarkPoolGetRemove1000Conns-4     5778          294           -94.91%
benchmark                             old allocs     new allocs     delta
BenchmarkPoolGetPut10Conns-4          0              0              +0.00%
BenchmarkPoolGetPut100Conns-4         0              0              +0.00%
BenchmarkPoolGetPut1000Conns-4        0              0 …
```
> Optimize pool.Remove.

- example_test.go
- internal/pool/conn.go
- internal/pool/conn_stack.go
- internal/pool/pool.go
- internal/pool/pool_test.go
```
benchmark                              old ns/op     new ns/op     delta
BenchmarkPoolGetPut10Conns-4           209           385           +84.21%
BenchmarkPoolGetPut100Conns-4          215           389           +80.93%
BenchmarkPoolGetPut1000Conns-4         236           388           +64.41%
BenchmarkPoolGetReplace10Conns-4       319           376           +17.87%
BenchmarkPoolGetReplace100Conns-4      294           409           +39.12%
BenchmarkPoolGetReplace1000Conns-4     294           410           +39.46%
benchmark                              old allocs     new allocs     delta
BenchmarkPoolGetPut10Conns-4           0              0              +0.00%
BenchmarkPoolGetPut100Conns-4          0              0              +0.00%
BenchmarkPoolGetPut1000Conns-4         0 …
```
> Make free-connection stack a LIFO.

- .travis.yml
- LICENSE
Go 1.4 race build timeouts 4 times of 5. I think it is easier to remove it, because I plan to add more race tests, not to remove/simplify existing race tests.
> Remove Go 1.4 from test build. Bump license.

- cluster.go
- error.go
- redis.go
This change makes cluster to retry command only in 2 cases:
- network error
- MOVED/ASK error response
Previously it retried on all error replies such as:
```
-ERR unknown command 'foobar'
-WRONGTYPE Operation against a key holding the wrong kind of value
```
etc
I took a chance to speedup `isMovedError` since it is called more often now.
> Cleanup error handling code.

- command.go
- command_test.go
- redis_test.go
This reverts https://github.com/go-redis/redis/pull/301 because
- string is slightly more preferable than []byte
- allocation number is the same
- previous change was backwards incompatible
> Convert bytes to string in Cmd.

- commands.go
- commands_test.go
This PR adds support for the `count` part of `SPOP key [count]` that was introduced in REDIS 3.2. The implementation follows the implementation of `SRandMemberN`.
> Add support for SPOP with a count argument

- cluster.go
- cluster_test.go
- command.go
- commands.go
- pipeline.go
- redis.go
- ring.go
- tx.go
Fixes https://github.com/go-redis/redis/issues/240. Example:
```
err := client.ForEachMaster(func(master *redis.Client) error {
keys, err := master.Keys("*")
return err
}
log.Println(keys)
})
```
> Add ForEachMaster API.

- README.md
This changes the links from redis.v3 documentation to redis.v4 documentation.
> Update README.md to use redis.v4 documentation

- commands.go
Fixes https://github.com/go-redis/redis/issues/341
> Rename Commander to Cmdable to match internal name.

- commands.go
This could be used to update metrics or debug/logging (#259).
There are many ways this could be done. I chose a way that involves minimal changes.
Example usage:
```
client = redis.NewClient(...)
client.WrapProcess(func(oldProcess func(cmd redis.Cmder) error) func(cmd redis.Cmder) error {
return func(cmd redis.Cmder) error {
before := time.Now()
err := oldProcess(cmd)
log.Println(`error running redis command "`, cmd, `": `, err)
} else {
log.Println(`running redis command "`, cmd, `" took `, time.Since(before))
}
return err
}
})
```
> add WrapProcess to allow users to alter command processing

- result.go
As per issue https://github.com/go-redis/redis/issues/353
I've not included tests because they're relatively simple, not for production use, and if I'm honest, I'm unfamiliar with the testing framework used.
Let me know if this is a problem and I'll write some up.
> Add Cmd constructors for testing/mock purposes.

- iterator.go
- iterator_test.go
Iterator may return empty page with non zero cursor.
I fix early return from iterator by "for" loop.
> fix iterator across empty pages

- options.go
Most users just don't know what to do when they see `redis: pool timeout`. New defaults should make situation much better for them.
> Set some sane default for every day usage.

- cluster.go
- options.go
This PR disables reap connection for cluster.
`ClusterOptions.clientOptions()` does not copy `IdleCheckFrequency` field, but `Options.init()` sets default parameter (1min).
So `ConnPool.reaper()` is enabled in `NewConnPool()`.
I'm not sure the concept to disable idle check for cluster connection is right decision but I follow the comment in `ClusterOptions.clientOptions()`
```go
// IdleCheckFrequency is not copied to disable reaper
```
If not, I'll create another PR to reflect IdleCheckFrequency from cluster options.
> Disable idle checks for cluster connection

- pubsub.go
Fixed bug when connection loss to server leads to exponential grow of channels and patterns slice in PubSub in every reconnect
> PubSub. Use appendIfNotExists instead of append for channels and patterns

- cluster.go
- cluster_client_test.go
- redis.go
To avoid a duplicate definition,
remove `Addr` field from `clusterNode`.
thanks!
> Remove Addr field from clusterNode

- cluster.go
- internal/errors/errors.go
I meet a problem in cluster; When slave failover, other slave will resync data from new master, if readonly is open, service can't get data in some minute. So I suggest to get data from new master in the sync duration.
> if readonly is open, read from master when slave is loading data

- main_test.go
- ring.go
- ring_test.go
There is problem with `eval` and `evalsha` commands.
`COMMAND INFO eval` returns first key position `0`.
After that, redis ring chooses `eval` as a value for sharding.
Then, if you try to delete created value, ring may choose another shard
and delete won't work.
Eval command should be parsed, to be sharded properly, according to
redis specs: http://redis.io/commands/command .
I've introduced a new flag in the `RingOptions`, which will enable new
behavior: `RouteByEvalKeys `.
If it is enabled, `cmdFirstKey` will check if function is  `eval` or
`evalsha` commands and will check if number of params -- `cmd.arg(2) != "0"`.
If it has parameters, it will return `3`, otherwise it will return `0`.
> Add new parameter to the RingOptions to override CommandInfo first key

- README.md
- redis.go
Two reasons:
1. Most people use some sort of vendor tools these days and they support semver, e.g. https://github.com/Masterminds/glide. You are using tags already!
2. The gopkg.in servers are unfortunately not as stable and robust as I wish they were. We have experienced several failures on builds, CI runs, etc because of non-200 responses.
Replaces #395
> Remove static import

- cluster.go
refactor `cluster.go`
Reduce elseif statements and distinguish between `errors.IsNetwork` and `errors.IsMoved`
```go
if errors.IsNetwork(err) {
...
break
}
moved, ask, addr := internal.IsMovedError(err)
if moved {
...
} else if ask {
...
} else {
...
}
```
Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-redis/redis/400)
> simplify if condition

- options.go
- options_test.go
This includes setting up a default dialer that handles the ssl
handshake.
We (Heroku) would like to move secure redis connections forward, but
have this chicken and egg problem with some drivers. Drivers for other
languages already support rediss://
> Add support for parsing redis:// and rediss:// URLs

- README.md
Correct me if I'm wrong, but it should by ZrangeBy not ZRangeByScore?
> Fixed Readme typo ZRangeBy

- commands.go
Allow HSET \ HSETNX to set value as interface{}.
Fix to #453
> PR try.v2 for issue #453

- pubsub_test.go
Seems like in Go 1.4 sometimes the error returned from pubsub.ReceiveMessage is "use of closed network connection" error instead of "redis: client is closed". 
This cause the go routine to fail before it marks the waitGroup which causes the test to wait forever 
This commit doesn't fix the test but at least the build will fail sooner.
> ensure wait.done to avoid deadlock in test

- commands.go
- commands_test.go
I found that the timeout of WAIT command is too short.
[The document](https://redis.io/commands/wait) says that the timeout is in milliseconds,
> If the timeout, specified in milliseconds, is reached, the command returns even if the specified number of slaves were not yet reached.
but go-redis treats it as seconds.
``` go
cmd := NewIntCmd("wait", numSlaves, int(timeout/time.Second))
```
I tried WAIT command actually(in redis 3.2.8).
`wait 1 1000` timed out in 1000ms = 1s.
``` plain
127.0.0.1:6379> role
1) "master"
2) (integer) 0
3) (empty list or set)
127.0.0.1:6379> wait 1 1000
(integer) 0
(1.07s)
```
> the timeout of WAIT command is in milliseconds.

- commands.go
To help people looking for it specifically.
(I just had a brief moment of madness: "Why was SETEX removed!?", until I found the [PR](https://github.com/go-redis/redis/pull/107), but I don't think everyone will use the GitHub search in such a desperation moment.)
> Mention SETEX in the documentation.

- command.go
> StringCmd: remove an unnessary type casting

- cluster.go
It should be using ClusterClient.TxPipeline() and not ClusterClient.Pipeline().
> Fix typo in ClusterClient.TxPipelined()

- pipeline_test.go
- redis.go
@vmihailenco Sorry, I've left one method returning the struct instead of the new interface, my bad...
Can you merge this and retag?
Thanks!
> Client TxPipeline method should also return a Pipeliner

- pipeline.go
- pipeline_test.go
- redis_test.go
- tx_test.go
Fixes https://github.com/go-redis/redis/issues/572
> Don't return an error when pipeline is empty

- internal/pool/pool.go
- internal/pool/pool_test.go
- main_test.go
- pubsub.go
- redis.go
- sentinel.go
- sentinel_test.go
Fixes https://github.com/go-redis/redis/issues/583
> Resent client pool when sentinel switches master

- cluster.go
- commands_test.go
Not sure if this is a redis bug or a feature, but we have recently noticed `CLUSTER SLOTS` suddenly reporting:
```
1) 1) (integer) 12290
2) (integer) 12697
3) 1) "10.0.0.120"
2) (integer) 6379
3) "906ad7f61c9173cc86a793e7bdfc9d204153476f"
4) 1) "127.0.0.1"
2) (integer) 6379
3) "e8e136bf028b88f4c7d5d64e73f134ed9b89dab6"
```
A similar issue was reported [here](https://github.com/luin/ioredis/issues/365)
> Use node address instead of relying on loopback reported by redis

- cluster.go
- options.go
- redis.go
- universal.go
As described in https://github.com/go-redis/redis/issues/603, this PR rename `ReadOnly` to `readOnly` so that it can only be used by a cluster client.
> Limit Readonly Option to cluster client only

- example_test.go
I've updated the example to show that Incr() can be used as an atomic operation, without Get() to retrieve key value afterwards.
> Using INCR as an atomic operation

- options_test.go
%q is a single-quoted character literal safely escaped with Go syntax. It doesn't need additional quotes.
> removed quotes surrounding %q

- internal/unsafe.go
there is a problem of converts by reflect.see example:
```go
package main
import (
"fmt"
"reflect"
"unsafe"
)
func main() {
fmt.Println(GetString())
}
// BytesToString converts byte slice to string.
func BytesToString(b []byte) string {
bytesHeader := (*reflect.SliceHeader)(unsafe.Pointer(&b))
strHeader := reflect.StringHeader{
Data: bytesHeader.Data,
Len:  bytesHeader.Len,
}
return *(*string)(unsafe.Pointer(&strHeader))
}
// StringToBytes converts string to byte slice.
func StringToBytes(s string) []byte {
sh := (*reflect.StringHeader)(unsafe.Pointer(&s))
bh := reflect.SliceHeader{
Data: sh.Data,
Len:  sh.Len,
Cap:  sh.Len,
}
return *(*[]byte)(unsafe.Pointer(&bh))
}
func GetString() string {
b := make([]byte, 8)
return BytesToString(b)
}
```
i use cmd：
```go
go build -gcflags="-m"
``` …
> fix unsafe.go 

- cluster.go
- example_instrumentation_test.go
- redis.go
- redis_context.go
- ring.go
Currently, there is only WrapProcess method in Client, not in other client. Besides, there is no method to instrument pipeline. This pull request implement WrapPipelineExecer method to instrument pipeline, and add WrapProcess and WrapPlinelineExecer to all clients
> Add WrapProcess and WrapPipelineExecer to all clients for better instrument support

- commands_test.go
- parser.go
When EVAL response contains a customized error, current parser will stop at this error and drop all remaining bytes.
Sample command.
eval 'return {12, {err="error"}, 34}' 0
In this sample, result of `client.Eval` doesn't include `34`.
> Correctly parse EVAL response containing customized error

- .gitignore
- Makefile
I could not run `make testdeps` on a mac. The change I have made to the inline-editing option syntax will allow the sed command to work with both GNU sed and BSD sed.
> Change Makefile to use sed syntax that will work for both GNU and BSD sed

- script.go
`SCRIPT EXISTS` accepts a hash, not the raw source: https://redis.io/commands/script-exists
> Script: Fix `Exists` to use hash instead of source

- universal.go
At the moment, instrumentation of `UniversalClient` is not possible without extra type conversion.
Could you add `WrapProcess` to the `UniversalClient` interface?
> add WrapProcess to UniversalClient interface

- cluster.go
This change just adds the option to balance any reads between a master and its replicas. It will be overridden if RouteByLatency is also set.
> Add option to balance load between master node and replica nodes

- cluster.go
The race looks like this and I don't understand what is happening
```
WARNING: DATA RACE
Write at 0x00c420c7f958 by goroutine 98:
sync/atomic.StoreInt32()
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/runtime/race_amd64.s:229 +0xb
github.com/go-redis/redis.(*clusterStateHolder).LazyReload.func1()
/home/travis/gopath/src/github.com/go-redis/redis/cluster.go:532 +0x7b
Previous write at 0x00c420c7f958 by goroutine 59:
??()
-:0 +0xffffffffffffffff
net.(*netFD).incref()
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/net/fd_mutex.go:200 +0x3e
net.setDeadlineImpl()
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/net/fd_poll_runtime.go:135 +0xad
net.(*netFD).setReadDeadline()
/home/travis/.gimme/versions/go1.8.7.linux.amd64/src/net/fd_poll_runtime.go:117 +0x61 …
```
> Re-order atomic field to please race detector

- cluster.go
- ring.go
This change adds the Context and WithContext methods to
ClusterClient and Ring, as we have in the regular Client
In these two cases, WithContext returns the same instance of the client, and not a copy. Copying is tricky and difficult in this case because the two contain mutexes (in clusterNodes).
Fixes #700
> cluster: add support for context.Context to ClusterClient and Ring

- cluster.go
- pubsub.go
When there are thousands of subscriptions and the rate of subscribe and unsubscribe is high (hundreds per seconds), appendIfNotExists and remove call perform very poorly and was consuming all the CPU. Replacing the slice with the map improved the performance (CPU before was at 90% afterwards came down to 10%). I also had the pprof profile before and after this change but I am not able to find it now.
> Remove costly 'appendIfNotExists' and 'remove' call from PubSub

- cluster.go
Fixes https://github.com/go-redis/redis/issues/773
The problem is `c.cmdable.setProcess(c.Process)` in the factory method. The reference to `c.Process` is specific to that instance. When we copy via `cp := *c`, the new client retains that reference, and thus methods invoked on the new client will end up calling `Process` on the old client.
To fix this, I took the same approach used in the non-cluster client: https://github.com/go-redis/redis/blob/master/redis.go#L361
> reset cmdable.process when copying cluster client

- cluster.go
- cluster_test.go
Fixes https://github.com/go-redis/redis/issues/775
Non-pipeline cluster client commands are routed using cmdSlotAndNode().
This changes pipeline cluster client commands to use that as well rather than always routing to master nodes.
> Use cmdSlotAndNode() to route ClusterClient pipeline commands

- options.go
see the issue: https://github.com/go-redis/redis/issues/799
Currently when redis.Options.TLSConfig is set, the redis.Options.Dialer function can hang indefinitely!
This change causes connection negotiation + tls handshaking to together be governed by the redis.Options.DialTimeout.
This seems to be the expected behavior, per the go standard library.  See for example:
https://golang.org/pkg/crypto/tls/#DialWithDialer
> Establishing TLS connections respect DialTimeout

- commands.go
- commands_test.go
go-redis supports old-style syntax of client kill command, and new syntax wasn't supported. This pr add new style syntax without breaking the old API by adding a new function `ClientKillByOption`.
old style syntax:
```
CLIENT KILL ip:port
```
new style syntax:
```
CLIENT KILL <option> [value] ... <option> [value]
```
> Supports new style syntax of client kill command

- command.go
- commands.go
- commands_test.go
The tests were synthesized out of `ZPop{Min,Max}` and `BLPop`.
Note, that order of return values (currently) mentioned on https://redis.io/commands/bzpopmin does not correspond to the actual order in 5.0 (see https://github.com/antirez/redis-doc/pull/997)
> Implement BZPop{Min,Max}

- redis.go
I had a race in my integration tests that ultimately boiled down to a subscription that wasn't always completing before the first publication. The debugging took a bit of spelunking and/or running across https://github.com/go-redis/redis/issues/575 to figure out. The behavior was surprising to me, but makes sense, so I figured a little documentation wouldn't hurt.
Haven't looked at the other client configuration Subscribe() methods. Would they benefit from a note as well?
Also, can it be expected that calling Receive() right after Subscribe() should always return a *Subscription?
> Add godoc about Receive call after Subscribe

- .travis.yml
- cluster.go
- commands_test.go
- options.go
- redis.go
This is an alternative to https://github.com/go-redis/redis/pull/874. Basically it defines rate limiter interface which allows to implement different limiting strategies in separate packages.
@xianglinghui what do you think? Is provided API enough to cover your needs? I am aware that code like https://github.com/go-redis/redis/blob/master/ring.go#L618-L621 requires some work in go-redis, but other than that it seems to be enough.
> Add Limiter interface

- commands.go
- commands_test.go
- https://redis.io/commands/xgroup `CREATE` supports an undocumented(https://github.com/antirez/redis-doc/issues/1007) `MKSTREAM` option.
Added support for it as a boolean parameter to the `XGroupCreate` method.
- ~Added `redis.BusyGroup` const, which represents the error returned by `XGROUP CREATE` if the group already exists(see https://redis.io/commands/xgroup docs)~
Note, that `mkStream` is a breaking API change, so maybe adding a `XGroupCreateMkStream` is a better option, which is also more consistent with `ZAddNX` and similar.
> xgroup: Add XGroupCreateMkStream

- example_test.go
- options.go
If the Addr value is not passed, use default host (`localhost`) and port (`6379`).
> Support default redis address

- cluster_test.go
- commands.go
[API Reference](https://redis.io/commands/cluster-getkeysinslot)
This change adds the `GETKEYSINSLOT` API, which fetches a list keys for a given key slot, given a max count of keys to fetch.
> Add GETKEYSINSLOT API call for Clustered Redis

- cluster.go
- command.go
Currently, the cluster command "GETKEYSINSLOT" passes in a keyslot as a parameter. This parameter needs to be recognized as the slot to use when executing the command. Currently, it ignores it and picks a random node. This PR fixes this issue.
> Cluster commands respecting keyslots from command input

- cluster.go
On reload redis cluster, pubSub do panic.
```
cn, err := node.Client.newConn()
// in this case cn still nil, but node not nil, 
// and next call newConn (from pubsub._conn) do panic
// we need set node to nil before return
node = nil
return nil, err
}
```
> fix pubsub panic on redis reload

- sentinel.go
Adds 3 x missing "sentinel" commands to SentinelClient:
1. .Masters()
1. .Slaves()
1. .CkQuorum()
See: https://redis.io/topics/sentinel#sentinel-commands
> Add .Master(), .Slaves() and .CkQuorum() funcs for Sentinel

- sentinel.go
This PR adds the following missing Sentinel commands:
1. .Ping()
1. .Monitor()
1. .Remove()
1. .Set()
See: https://redis.io/topics/sentinel#sentinel-commands
> Add SentinelClient Ping, Monitor, Remove and Set funcs

- Makefile
- cluster.go
- go.mod
Fixes https://github.com/go-redis/redis/issues/1031
> Mark node as loading in Cluster pipeline read

- sentinel.go
Last version of sentinel support password (AUTH)
From: https://redis.io/topics/sentinel
> You can also configure the Sentinel instance itself in order to require client authentication via the AUTH command, however this feature is only available starting with Redis 5.0.1.
> Before using this configuration make sure your client library is able to send the AUTH command to Sentinel instances.
I add a new option in failover options that is PasswordSentinel that can be different from Redis Database.
Tested and working.
> add option for sentinel password

- cluster.go
- ring_test.go
Replaces https://github.com/go-redis/redis/pull/1001
Fixes https://github.com/go-redis/redis/issues/945
> Use master / another slave node when current node is failing

- sentinel.go
Fixes https://github.com/go-redis/redis/issues/1071
> Use Dialer in Sentinel failover when available

- result.go
Needed to create ZWithKeyCmd  while testing ZPOPMIN opertaions, found it missing in results.go
> Add NewZWithKeyCmdResult to initialize ZWithKeyCmd for testing

- ring.go
- ring_test.go
This PR enhances the `Ring` client by adding a new `Passwords` field to it so that each shard can have its own password. This change doesn't introduce a breaking change since the existing `Password` field has precedence over the new one and applications already using the `Ring` client with a single password won't stop working.
> Add support for individual passwords for ring shards

- command.go
Updates https://github.com/go-redis/redis/issues/472
Before
```
BenchmarkRedisSetGetBytes-4   	   41136	     28640 ns/op	   20777 B/op	      11 allocs/op
```
After
```
BenchmarkRedisSetGetBytes-4   	   43369	     26224 ns/op	   10537 B/op	      10 allocs/op
```
> Use unsafe StringToBytes to speedup StringCmd.Bytes

- internal/pool/pool.go
If addIdleConn() stopped due to the error, poolSize and idleConnsLen will be confusing.
> protect pollSize and idleConnsLen with mutex

- options.go
- redis_test.go
Use net.Dialer DialContext by default because go-redis supports contexts.
Resolves #1101
> Use DialContext by default

- internal/error.go
- internal/pool/pool_single.go
This is a bugfix for issue #1113.
This is intended to solve the issue while making as few other changes as possible. Since `SingleConnPool` is not used in any other context, this seemed reasonable.
I'm completely open to alternative ways to solve this, but the essence is that `SingleConnPool.Remove` _must_ flag the pool as no longer able to return a valid connection.
> Close single conn connection pool

- go.sum
There's a wrong dependency in go.sum, will result in `//indirect` imports in go.mod.
Basically this MR solves the same issue as https://github.com/go-redis/redis/pull/1000
> fix go.sum with go mod tidy

- internal/pool/pool.go
This CL makes ConnPool exit immediately when the client is closed.
Fixes #1029
> internal/pool: exit conn pool fast

- pubsub.go
This addresses the issue where the client is stuck in a loop of "redis: discarding bad PubSub connection" while failing to receive subscription messages. 
The following sequence causes this stuck state:
healthy is initialized to true.
Timer event fires, a new Ping command is issued, and healthy = false.
Another timer event fires before the ping response, a new Ping command is issued but the connection is dropped by c.reconnect before a response can be received.
The client will remain in this reconnect loop since there is no way to set healthy = true. This PR sets healthy = true after the reconnect, which allows the next timer event's Ping response to arrive before another reconnect.
> Fix "redis: discarding bad PubSub connection" stuck state

- README.md
Earlier code will result in exception:
`assignment mismatch: 2 variables but client.baseClient.Do returns 1 values`
> Fix code typo in README sample code

- sentinel.go
why FailoverOptions like MinIdleConns not trans to Options?
> fix: FailoverOptions to Options

- main_test.go
I am working on a mac and I was having a number of issues running the tests. One of them being that the default redis config seemed to be in the wrong place. I am not sure if I the config was supposed to be placed at the existing `redisServerConf` by some script, but I needed to make this change to have it work properly. 
If I am doing something wrong and I should not need to make this update let me know.
> properly point redisServerConf to redis.conf

- result.go
GeoPosCmd cannot mock in unit test due to set result function is missing.
> add NewGeoPosCmdResult to make GeoPos mockable result

- README.md
Hi, I found the sample code for `Sort()` method missed the `&` symbol，because of the signature of `Sort()` method `func (c *Client) Sort(key string, sort *Sort) *StringSliceCmd` says it need a pointer of `redis.Sort{}`
> Fix sample code for Sort method in README

- universal.go
**Why is it necessary?**
The built-in `NewUniversalClient` function logic is not compatible with our logic. Therefore, we wanted to implement our logic. The following is our code snippet:
```
if opts.MasterName != "" {
client = redis.NewFailoverClient(opts.failover())
} else if cfg.EnableCluster {
client = redis.NewClusterClient(opts.cluster())
} else {
client = redis.NewClient(opts.simple())
}
```
To handle it, I copied private `failover`, `cluster` and `simple` functions to my repo redundantly. If they were public, it would be very useful. See: https://github.com/TykTechnologies/tyk/blob/c7634e7703796ea64c1cc21d663e45de3b0970cf/storage/redis_cluster.go#L174-L275
If you are ok with this change, I can add comments to those functions with your guidance.
> Make universal options functions public

- command.go
- commands_test.go
XReadGroup stops processing a Redis Stream if any item in the stream is deleted by XDel or XTrim (or XAdd with Maxlen). It returns a `RedisError("redis: nil")` and stop processing the rest items in the stream, which makes XReadGroup not usable in some realistic scenarios (e.g. It is typical to call XTrim to limit the Redis Stream size).
This problem does not exist in Redis CLI. See the example below. 
In the Redis CLI console, if we delete an item (1579681634428-1) from a stream (str0), we can still get the rest items from this stream correctly. Redis CLI shows the deleted item as (nil). Based on the [Redis Protocol](https://redis.io/topics/protocol), this makes perfect sense because Redis server returns `*-1\r\n` for the deleted items in the stream.
```
127.0.0.1:6379> xreadgroup Group …
```
> let XReadGroup skip empty message and process next message

- cluster.go
- options.go
Fixes https://github.com/go-redis/redis/issues/1198
> Set error on the commands in case there are no more attempts left

- README.md
I was going through the quickstart and got tripped up by the `client` variable being used in the `ExampleClient()` function without initialization. I assumed that it's implied that you have to initialize it first when actually running it but I thought this would make it more explicit and clear.
> README Fix: Added client variable initialisation (redis.NewClient) in quickstartExampleClient()

- CHANGELOG.md
- commands.go
- commands_test.go
Fixes https://github.com/go-redis/redis/issues/1262
Closes https://github.com/go-redis/redis/pull/1246
Closes https://github.com/go-redis/redis/pull/1245
> Rename HMSet to HSet and restore old HMSet

- ring.go
- ring_test.go
There's currently no way to specify a TLS configuration for a Redis Ring setup. This adds configuration for this so it can be set up in a similar way as the password, with either a single one for all shards or a
configuration per shard.
> Add client instantiation callback to allow more flexible configuration

- ring.go
`cmdsInfo` at the moment sets the `firstErr` to the fallback option, which means line 518 would never execute, and the actual error would be masked.
(For example, I just had to track this down because I was trying to use Redis 6, and it isn't compatible)
> cmdsInfo to actually use and return the first error

- pubsub.go
This change causes func `newMessage` to assert `reply[1].(string)` safely and prevents the function from panicking. This one closes #1319.
> Prevent panic during nil to string type assertion

- cluster.go
code users can pass a limiter struct into cluster client then allow each node client in the cluster to use that limiter
> allow cluster client to use limiter

- error.go
- internal/proto/reader.go
Fixes https://github.com/go-redis/redis/issues/1295
Closes https://github.com/go-redis/redis/pull/1296
> Add redis.Error interface and export ErrClosed

- command.go
- command_test.go
- internal/proto/write_buffer_test.go
- internal/proto/writer.go
Hi,
Time package has nanosecond precision.
Actually go-redis removes this precision when time is stored or fetched with RFC3339.
```
t := time.Now() // time with nanoseconds precision
_ := redisClient.Set("my-time", t, 0).Err()
ft, _ := redisClient.Get("my-time").Time() 
// ft != t
```
To deal with these nanoseconds, I suggest RFC3339Nano.
> Store time in RFC3339Nano to keep nanoseconds

- cluster.go
Replaces https://github.com/go-redis/redis/pull/1316
Can be used like this
```
rdb := redis.NewClusterClient(&redis.ClusterOptions{
Addrs: []string{":7000", ":7001", ":7002", ":7003", ":7004", ":7005"},
NewClient: func(opt *redis.Options) *redis.Client {
opt.Limiter = getLimiter(opt)
return redis.NewClient(opt)
},
})
```
> Add ClusterOptions.NewClient hook

- ring.go
As of v8-beta1, Ring can no longer executes 'AUTH password' now. This is meant to fix that. See issue https://github.com/go-redis/redis/issues/1370 for rationale.
> Re-added password support for AUTH purposes

- commands.go
- commands_test.go
This PR solves the problem described in https://github.com/go-redis/redis/issues/1388.
Previously, `XAddArgs.Values` was of type `map[string]interface{}`. Now, it is `interface{}`. This change is backward compatible.
This change uses `appendArgs` utility function in `XAdd`. It was extended to support `[]interface{}` for the first item in the `src` slice. This might be a bit controversial as `appendArgs` is not used directly like that anywhere else. If so, I will rewrite this fragment not to use `appendArgs`.
> Add support for slices in XAddArgs.Values

- cluster.go
During loading state, if all the nodes can't be connected, it's
possible that all the nodes' IP addresses have changed at the same
time. Clear the clusterAddrs so that the cluster client has chance
to get updated nodes' IP addresses by using the initial setting of
cluster addresses.
> Make cluster client get updated nodes' addrs

- internal/pool/pool.go
This makes the reading and writing of lastDialError from the pool
faster, as atomic.Value is much more lightweight than the mutex.
Note that using error in atomic.Value directly could cause panics,
because errors could have inconsistent types. Thus wrap them with a
simple struct.
> Use atomic.Value instead of lock for ConnPool.lastDialError

- options.go
The default DialTimeout will not take effect when opt.DialTimeout is zero and opt.Dialer is nil.
> feat(option): default dialtimeout take effect when dialer is nil

- cluster.go
There is was a nil pointer dereference when all nodes are failing, It was described early in this issues #1416 and #1401
> fix nil node dereference when use RouteByLatency in cluster

- iterator.go
I'm reusing this for disque client... and get index out of bounds error because there really are just 2 items in array not 3.
BTW.. is it possible to merge this down to 6.x series as we really don't want to do an upgrade
> Prevent index out ouf bunds error

- options.go
- sentinel.go
Allow `FailoverClient` `ReadOnly` option. Client then connects to redis replicas (or master if no slave is available) for performing read-only queries. User is responsible for deciding which query can be run against it.
It aims to implement the same as #997 but without misusing ClusterClient which is not suitable for this.
> FailoverClient with read-only support

- pubsub.go
- pubsub_test.go
Hi, I'd like to add the support of string array in pubsub message payload.
Since when enabling the ["Redis server-assisted client side caching"](https://redis.io/topics/client-side-caching) feature with RESP2 and Redis 6, the redis-server could send string array payload which contains keys to invalid via the pub/sub message.
This PR stores the string array payload into a new field `PayloadSlice` of the pubsub`Message` struct for not breaking the  existing code that using the existing `Payload` field.
This PR is far from a complete client side caching solution, but at least this may let user be able to use this new redis feature with this library.
> Support string array in pubsub message payload

- redis.go
Fixes https://github.com/go-redis/redis/issues/1478
@kaka19ace please review.
> Make sure to call after hook on error

- cluster.go
- command.go
- ring.go
In this method, аfter cloning `ClusterClient` instance, `cmdsInfoCache` will still use context from the original. Small fix for this.
> Fix not applying updated ClusterClient context after calling WithContext method

- pipeline_test.go
- redis.go
This is caused by function `wrapMultiExec` sometimes clobbering the caller's
cmd slice, corrupting future requests.
> Fixes #1386; pipeline.Exec() sometimes returns spurious `StatusCmd`

- internal/proto/reader.go
- internal/proto/reader_test.go
I get this issue when retrieving large blobs from [redix](https://github.com/alash3al/redix) which is API compliant with redis.
I created a test that reproduces that error. It happens when reading from a byte array which length is larger than 4096.
See also #641
The blob should be read in full.
An error is returned.
See, patch in this PR.
See the added test case in this PR which (when ran without the fix added) would result in the following:
```bash
❯ go test internal/proto/reader.go internal/proto/reader_test.go 
--- FAIL: TestReader_ReadLine (0.00s)
reader_test.go:51: Should be able to read the full buffer: bufio: buffer full
reader_test.go:55: Values must be equal: ""
FAIL
FAIL	command-line-arguments	0.272s
FAIL
```
> Fixes bufio buffer full error when reading from an array larger than 4096 bytes

- commands.go
- commands_test.go
- example_test.go
I'm aware that, in essence, the `Set` function can do everything that `SetEX` function can do, however, I'm using this library to test a Redis-compatible server implementation, and due to the fact that there's no way to send the `SETEX` command using go-redis/redis, I'm unable to fully test the aforementioned Redis-compatible server.
Assuming this reasoning is fine with you, one of my concerns is that the order in which `SETEX` takes an argument is the following:
```
SETEX key seconds value
```
But in order to be consistent with other functions, I opted to use the following function signature:
```
SetEX(ctx context.Context, key string, value interface{}, expiration time.Duration)
```
What do you think?
> Add SetEX command

- error.go
We should also try again when the error is CLUSTER_REDIR_UNSTABLE.
https://github.com/redis/redis/blob/380f6048e0bbc762f12fa50b57b73cf29049f967/src/cluster.c#L5838-L5840
> CLUSTER_REDIR_UNSTABLE error should be retry

- .github/workflows/go.yml
- .golangci.yml
- .travis.yml
- internal/proto/scan.go
- internal/util.go
- options.go
- redis.go
Disable some new linters.
And removed unnecessary intenal util function.
> Update golangci-lint to v1.32

- sentinel.go
we can reproduce it with the below piece of code:
```go
func TestFailoverClient(t *testing.T) {
options := redis.FailoverOptions{
SentinelAddrs: []string{"127.0.0.1:26379"},
MasterName:    "mymaster",
}
client := redis.NewFailoverClient(&options)
var waitGroup sync.WaitGroup
for i := 0; i < 10; i++ {
waitGroup.Add(1)
go func() {
defer waitGroup.Done()
v, err := client.Get(context.TODO(), "no_exists_key").Result()
assert.Empty(t, v)
assert.Equal(t, err, redis.Nil)
}()
}
waitGroup.Wait()
}
```
run it some times with -race flag enabled and would get the data race warning(It seems no harm even we don't fix it, but may annoy someone who uses the `FailoverClient` in the test case with the data race detect flag enabled.):
```
redis: 2020/11/19 20:09:09 sentinel.go:607: sentinel: new …
```
>     FIX: data race warning in sentinel client since the newConnPool would spawn the new goroutine and use the onFailover at the same time.

- error.go
- main_test.go
- race_test.go
- redis.go
Fixes https://github.com/go-redis/redis/issues/1571
Fixes https://github.com/go-redis/redis/issues/1568
> Close the conn on context timeout

- sentinel.go
The original text `all sentinels are unreachable` can sometimes be misleading, making some users think that all of their redis sentinels are down.
But it might not be the reality especially when using kubernetes and specify `c.sentinelAddrs` with the Service's domain. In this case, when the sentinel to which the domain is redirected runs into some errors despite other sentinels running healthily, the original text given by redis client will be confusing and delivering false message!
Just got out of a similar dilemma after checking the source code, feel free to correct me if I am wrong :)
> make error message for unreachable sentinels more clear

- cluster.go
- cluster_test.go
As discussed on discord @vmihailenco this PR adds support to export commands that give the replica and master for a given key.
> Add support to get cluster replica node for a given key

- options.go
Since 0 will not disable max retries (defaults to 3), add an explicit comment regarding how to disable.
> add disable/-1 comment to max retries

- cluster.go
- cluster_test.go
You have to set the ReadOnly flag on the ClusterOptions to make it fall back to
non-master nodes on reads. For non-clustered situations where you have multiple
nodes in a single ClusterSlot, it made the non-master node useless because it would
never route requests to it and if you set ReadOnly=true it would issue a READONLY
command to it, which would fail.
See comment in code for more details.
I believe this is a better fix for https://github.com/go-redis/redis/issues/869 than what was previously done in that it allows better use of redis instances.
> ClusterSlots Config and ReadOnly

- commands.go
- commands_test.go
- example_test.go
As of version 6.0 you can use this 'type' option to ask SCAN to only
return objects that match a given type, allowing you to
iterate through the database looking for keys of a specific type.
> Add ScanType command to Scan with 'type' option

- tx.go
This PR ensures that `Watch` will close the transaction if the user provided function `panic`s. 
Panics which occur inside `fn` but are recover outside of it render the client unusable (the connection pool never recovers since `tx.Close` is never called).
> Ensure Watch closes the transaction on panic

- command.go
- commands_test.go
- example_test.go
- internal/hscan/hscan.go
- internal/hscan/hscan_test.go
- internal/hscan/structmap.go
The package uses reflection to decode default types (int, string etc.) from Redis map results (key-value pair sequences) into
struct fields where the fields are matched to Redis keys by tags.
Similar to how `encoding/json` allows custom decoders using`UnmarshalJSON()`, the package supports decoding of arbitrary
types into struct fields by defining a `Decode(string) error`function on types.
The field/type spec of every struct that's passed to Scan() is cached in the package so that subsequent scans avoid iteration
and reflection of the struct's fields.
Issue: https://github.com/go-redis/redis/issues/1603
> Add redis.Scan() to scan results from redis maps into structs.

- fuzz.go
This PR adds a fuzzer.
Fuzzing is a way of testing programs whereby pseudo-random data is passed to a target function with the goal of finding bugs and vulnerabilities.
I have been working on running this fuzzer continuously on OSS-fuzz's platform, and I will be happy to integrate go-redis into the project so that this fuzzer can run continuously. OSS-fuzz is a free service for open source projects, and if bugs are found an email with a link to a detailed bug report is sent out to the maintainers on the mailing list. The mailing list is public and can be changed at any time, and there is a public disclosure policy of 90 days.
> Add fuzzer to integrate go-redis into OSS-fuzz

- fuzz/fuzz.go
As the fuzzer was moved, a few small changes are necessary to make it run.
> Fixed broken fuzzer

- command.go
- commands.go
- commands_test.go
add function "XInfoConsumers" as "XInfoGroups", tested on redis 6.0.10
btw: refer to [xinfo](https://redis.io/commands/xinfo) document, these codes may not workable in future redis release
> Note that you should not rely on the fields exact position, nor on the number of fields, new fields may be added in the future. So a well behaving client should fetch the whole list, and report it to the user, for example, as a dictionary data structure. Low level clients such as C clients where the items will likely be reported back in a linear array should document that the order is undefined.
> support "XINFO CONSUMERS"

- go.mod
- internal/instruments.go
function `otel.Meter` has been [moved](https://github.com/open-telemetry/opentelemetry-go/commit/9b242bc4015d82acd63614a9e9ddba0cd1bceca8#diff-a07b5af0fea95be688fdc26a39e3b3aed8d3f4a2adba86258a393566f8b82fc6) to `otel/metric/global.Meter` in OpenTelemetry 0.17.0.
> Update OpenTelemetry to 0.17.0 and fix "undefined: otel.Meter"

- Makefile
- commands.go
- commands_test.go
SetArgs supports all the SET command options. 
It is the alternative to the Set function when the user wants more control over the SET options.
> Add SetArgs command

- ring_test.go
possible errors：
```go
/redis/ring_test.go:366
respects max size on multi [It]
/redis/ring_test.go:535
Expected
<int>: 1
to equal
<int>: 0
/redis/ring_test.go:560
OR:
/redis/ring_test.go:366
respects max size on multi [It]
/redis/ring_test.go:535
Expected
<int>: 10
to equal
<int>: 9
/redis/ring_test.go:560
```
this test checks the number of `pool.conn`, if the health check is performed at the same time conn will be used, resulting in an abnormal number of `pool.conn`.
> solve possible unit test errors in ring_test.go

- pool_test.go
possible errors：
```go
/redis/pool_test.go:13
reuses connections [It]
/redis/pool_test.go:119
Expected
<uint32>: 98
to equal
<uint32>: 99
/redis/pool_test.go:148
```
Code:
```go
It("reuses connections", func() {
for i := 0; i < 100; i++ {
val, err := client.Ping(ctx).Result()
Expect(err).NotTo(HaveOccurred())
Expect(val).To(Equal("PONG"))
}
pool := client.Pool()
Expect(pool.Len()).To(Equal(1))
Expect(pool.IdleLen()).To(Equal(1))
stats := pool.Stats()
Expect(stats.Hits).To(Equal(uint32(99)))
Expect(stats.Misses).To(Equal(uint32(1)))
Expect(stats.Timeouts).To(Equal(uint32(0)))
})
```
because `opt.IdleTimeout = 1 * time.Second` and `conn.UsedAt` are unix timestamps.
if 100 times `client.Ping()` exceeds 1 second, `conn.deadline()` will be triggered to drop the connection, `conn.Get()` will …
> fix unit test errors that may appear in pool_test.go

- commands.go
- commands_test.go
SetArgs is amazing! It would be even more amazing to be able to use it
within a non-transactional Pipeline.
> Make SetArgs available to Pipeliner

- ring_test.go
fix the possible `data race`, details:
WARNING: DATA RACE
Read at 0x00c000302618 by goroutine 27:
github.com/go-redis/redis/v8_test.glob..func20.11.3.2()
/redis/ring_test.go:219 +0x1a4
github.com/go-redis/redis/v8_test.(*hook).AfterProcess()
/redis/main_test.go:429 +0x9a
github.com/go-redis/redis/v8.hooks.process()
/redis/redis.go:81 +0x24a
github.com/go-redis/redis/v8.(*Client).Process()
/redis/redis.go:617 +0x215
github.com/go-redis/redis/v8.(*Ring).process()
/redis/ring.go:603 +0x14e
github.com/go-redis/redis/v8.(*Ring).process-fm()
/redis/ring.go:589 +0x7e
github.com/go-redis/redis/v8.hooks.process.func2()
/redis/redis.go:75 +0x326
github.com/go-redis/redis/v8.hooks.withContext()
/redis/redis.go:134 +0x2e7
github.com/go-redis/redis/v8.hooks.process()
/redis/redis.go:74 +0x2e6 …
> fix ring test `Process hook` data race

- main_test.go
- race_test.go
- redis_test.go
- sentinel.go
- sentinel_test.go
Fix possible unit test errors:
```go
• Failure [1.005 seconds]
Client
/redis/redis_test.go:50
should update conn.UsedAt on read/write [It]
/redis/redis_test.go:242
Expected
<bool>: false
to be true
/redis/redis_test.go:259
```
```go
• Failure in Spec Setup (BeforeEach) [0.011 seconds]
Sentinel
/redis/sentinel_test.go:12
supports DB selection [BeforeEach]
/redis/sentinel_test.go:94
Unexpected error:
<*net.OpError | 0xc0009fb1d0>: {
Op: "dial",
Net: "tcp",
Source: nil,
Addr: {
IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 127, 0, 0, 1],
Port: 9125,
Zone: "",
},
Err: {Syscall: "connect", Err: 0x6f},
}
dial tcp 127.0.0.1:9125: connect: connection refused
occurred
/redis/sentinel_test.go:23
```
```go
• Failure [15.015 seconds]
Sentinel
/redis/sentinel_test.go:12
should facilitate failover [It] …
```
> fix test error

- sentinel.go
why is the value of name used as addr here, it should be wrong.
```go
func (c *sentinelFailover) discoverSentinels(ctx context.Context) {
sentinels, err := c.sentinel.Sentinels(ctx, c.opt.MasterName).Result()
internal.Logger.Printf(ctx, "sentinel: Sentinels master=%q failed: %s", c.opt.MasterName, err)
return
}
for _, sentinel := range sentinels {
vals := sentinel.([]interface{})
for i := 0; i < len(vals); i += 2 {
key := vals[i].(string)
if key == "name" {
sentinelAddr := vals[i+1].(string)
if !contains(c.sentinelAddrs, sentinelAddr) {
internal.Logger.Printf(ctx, "sentinel: discovered new sentinel=%q for master=%q",
sentinelAddr, c.opt.MasterName)
c.sentinelAddrs = append(c.sentinelAddrs, sentinelAddr)
}
}
}
}
}
```
--------------------------------------
In the …
> discoverSentinels read the addr field incorrectly

- cluster_commands.go
- cluster_test.go
Changes:
`ScriptLoad` loads script to all shards of the cluster.
`ScriptFlush` removes scripts from all shards of the cluster.
`ScriptExists` checks all shards of the cluster and returns false if any of the shards returned false.
Closes #1725
> ScriptLoad, ScriptExists and ScriptFlush for ClusterClient

- sentinel.go
Introduced in 8b19c310495637fb61e2b237abdedca922aced9a but all references were removed in 8d9ebc8459c6d3925c61ce3da78ac17118a118fd
> sentinel: removed unused field QuerySentinelRandomly

- .github/workflows/build.yml
- bench_decode_test.go
- cluster.go
- cluster_test.go
- command.go
- commands.go
- commands_test.go
- example_test.go
- go.mod
- internal/pool/conn.go
- internal/proto/reader.go
- internal/proto/reader_test.go
- internal/proto/writer.go
- pubsub_test.go
- redis.go
- result.go
- ring_test.go
- sentinel.go
- sentinel_test.go
1. Support redis RESP3 protocol, can work under RESP2 and RESP3.
2. If redis-server version >=6.0, RESP3 protocol is enabled by default. Otherwise use RESP2 protocol (redis < 6.0).
3. Remove test `Subscribe __redis__:invalidate`, it only works in RESP2 mode(redis6.0+).
4. `$EOF:<40 bytes marker><CR><LF>` and `*?<CR><LF>` that have not been enabled by redis-server have not been implemented for the time being, they will be followed up in the future.
> Add support for resp3 protocol

- commands_test.go
- redis_test.go
The client used in some tests is mistaken.
> Use the right redis client in tests

- pubsub.go
- pubsub_test.go
Improve pubsub, follow #1747 
ADD `ChannelMessage/ChannelSubscriptionMessage`,  mark `Channel/ChannelSize/ChannelWithSubscriptions` as `Deprecated` and remove it in v9.
Add ping command waiting time (healthTimeout), default 5 seconds.
ADD option: `WithChannelSize` `WithPingTimeout` `WithHealthTimeout`
> Improve pubsub

- command.go
- commands.go
- commands_test.go
Closes https://github.com/go-redis/redis/issues/1686
Redis docs: https://redis.io/commands/xautoclaim
I don't think `ID` is the right name for the cursor returned by Redis, but not sure what would be better. https://github.com/go-redis/redis/pull/1780/files#diff-4d7d1923693fc5ce892add2ea2907a744e77ea0b50c1939ccc5067cb48a466a3R1505
> Add XAutoClaim command

- commands.go
- commands_test.go
New commands and options:
- ZAdd GT and LT options ( #1789 )
- ZRange ByScore,ByLex,Rev and Limit options
- New cmd ZRangeStore
- New cmd ZUnion
New API：
- ZAddArgs 
- ZAddArgsIncr 
- ZRangeArgs 
- ZRangeArgsWithScores 
- ZRangeStore 
- ZUnion 
- ZUnionWithScores 
API marked `Deprecated` and removed in V9:
- ZAddNX 
- ZAddXX
- ZAddCh
- ZIncr
- ZAddNXCh
- ZAddXXCh
- ZIncrNX
- ZIncrXX
> Upgrade the <sorted set> series of commands

- commands.go
> Explain the use restrictions of KeepTTL.

- cluster.go
- options.go
`runtime.GOMAXPROCS()` is used instead of `runtime.NumCPU()` to detect a default pool size.
We are running our services in the Kubernetes cluster and usually, each of them consumes (and is limited to) 2-3 CPUs. 
But it's a logical restriction and `runtime.NumCPU()` will return all available CPUs on the _node_(64 in our case). 
That's why we set the `GOMAXPROCS` env variable to improve system's performance.
In the current implementation, each of our services can create 5 * 64 connections to each Redis node, which in our case means ~300 * 5 * 64 = ~100k connections to the single node (if I'm not mistaken)
Thanks to the lazy connection initialization it happens rarely and completely unexpected. Once service or Redis node is busy the client starts generating a huge number of connections:
The …
> GOMAXPROCS usage instead of NumCPU for the pool size

- cluster.go
- internal/pool/pool.go
- options.go
- ring.go
- sentinel.go
- universal.go
Linked issue: #1819 
Allows the user to choose between fifo and lifo pool via passing in the PoolType variable into redis.Options.
> Allow FIFO pool in redis client

- cluster.go
We encounter errors during Redis failover with `RouteRandomly` set to `true`.
After some debugging we found that `Failing` is never checked when serving random node for the slot.
This should be pretty easy to reproduce:
1. Start cluster using this docker-compose service:
```
redis-cluster:
image: grokzen/redis-cluster:6.0.9
container_name: redis-cluster.go-redis-test
environment:
- "IP=0.0.0.0"
ports:
- 7000-7005:7000-7005
```
2. Connect to cluster, perform read/write operations
3. `docker-compose exec redis-cluster supervisorctl stop redis-2`
> Check Failing() before serving random node

- internal/pool/conncheck.go
- internal/pool/conncheck_dummy.go
- internal/pool/conncheck_test.go
- internal/pool/main_test.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- main_test.go
- pool_test.go
- sentinel_test.go
- tx_test.go
it's work
Benchmark with Ping(No bad conns):
cpu: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
Benchmark_Ping_before-8   	 4014712	       289.7 ns/op	     164 B/op	       4 allocs/op
Benchmark_Ping_after-8    	 4029973	       286.7 ns/op	     164 B/op	       4 allocs/op
Benchmark_Ping_before-8   	 4039963	       290.5 ns/op	     164 B/op	       4 allocs/op
Benchmark_Ping_after-8    	 4077626	       290.2 ns/op	     164 B/op	       4 allocs/op
Benchmark_Ping_before-8   	 4018032	       285.9 ns/op	     164 B/op	       4 allocs/op
Benchmark_Ping_after-8    	 4074387	       292.3 ns/op	     164 B/op	       4 allocs/op
> ConnPool check  fd for bad conns

- command.go
- commands.go
- commands_test.go
`GeoRadius` and `GeoRadiusByMember` have been deprecated, we will not change them anymore.
> add cmd: geosearch, geosearchstore

- Makefile
- cluster.go
- cluster_test.go
- command.go
- command_test.go
- commands.go
- commands_test.go
- export_test.go
- internal/proto/writer.go
- options.go
- pipeline.go
- pool_test.go
- redis_test.go
- ring.go
- ring_test.go
merge master, and fix #1553, #1676
> adjust the code

- command.go
This is useful when Redis returns a slice.
> Add Cmd.Slice helper to cast to []interface{}

- internal/pool/export_test.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- internal/proto/reader.go
linked: #1861
When the connection pool is closed, we will still add new connections to the connection pool, and this part of the connection cannot be closed.
It may also cause errors such as `Stats`, as described in #1861
I added a count of `runGoroutine`, I am not sure if adding it is a good decision, although it is only for testing.
@vmihailenco Do you have any ideas?
> after the connection pool is closed, no new connections should be added

- example_test.go
- options.go
- options_test.go
In my Go programs, I usually want to modiffy the database connection options using CLI flags or environment variables. For example, to tune Postgres connections, I can set an environment variable like
```sh
PG="postgres://user@localhost:5432/testdb?sslmode=verify-full&connect_timeout=10" ./myprog
```
This is very handy for containerized applications.
In the Go program, one only needs to pass that string into `ParseConfig`:
```go
config, err := pgx.ParseConfig(os.Getenv("PG"))
conn, err := pgx.Connect(config)
```
With the Go Redis library, this is not so simple:
```go
_, err := redis.ParseURL("redis://localhost/0?dial_timeout=10")
//=> redis: no options supported
```
Here, the library requires me to either setup and parse additional flags/env vars, or extract the parameters from the URL …
> Allow query parameters for ParseURL

- main_test.go
- sentinel.go
- sentinel_test.go
👋🏾 Hey There!
Hopefully this is a pretty straightforward one. I have a redis installation that I'm trying to leverage that has Redis6 ACL auth against the Sentinels. This exposes a `SentinelUsername` field that propagates down to the underlying client (which already switches between Redis < 6 auth and ACL auth).
While I was there, I added a new test suite for the ACL'd sentinels!
> feat: add acl auth support for sentinels

- command.go
> feat: add SetVal method for each command

- error.go
- pubsub.go
- redis.go
This issue was surfaced in a Cloud Provider solution that used for
rolling out new nodes using the same address (hostname) of the nodes
that will be replaced in a Redis Cluster, while the former ones once
depromoted as Slaves would continue in service during some mintues
for redirecting traffic.
The solution basically identifies when the connection could be stale
since a MOVED response will be returned using the same address (hostname)
that is being used by the connection. At that moment we consider the
connection as no longer usable forcing to recycle the connection.
> Fix Redis Cluster issue during roll outs of new nodes with same addr

- error.go
@vmihailenco sorry but received some feedback from my colleagues and they suggested, which I agree, that by adding an space before the addr will remove any chance of having a false positive because of overlapping in the hostname.
Tested and works like a charm also.
> fix: add whitespace for avoid unlikely colisions

- bench_test.go
- commands.go
In some cases number of pre-allocated places in argument array is missing 1 or 2 elements, which results in re-allocation of twice as large array.
Particularly XRead's off-by-one smaller pre-allocation is responsible for up to 10% of total allocated memory in our prod application.
> Update some argument counts in allocs.

- commands.go
Hi ^^
Small commit to add ExpireNX, ExpireXX, ExpireGT and ExpireLT of Redis v7
doc: https://redis.io/commands/expire
Didn't manage to run the tests in local :'(
Associated issue: https://github.com/go-redis/redis/issues/1862
> Add redis v7's ExpireNX, ExpireXX, ExpireGT, ExpireLT

- go.mod
- go.sum
This PR updates the `go` directive in `go.mod` file by running `go mod tidy -go=1.17` to enable [module graph pruning](https://golang.org/ref/mod#graph-pruning) and [lazy module loading](https://golang.org/ref/mod#lazy-loading).
**Note 1:** This does not prevent users with earlier Go versions from successfully building packages from this module.
**Note 2:** The additional `require` directive is used to record indirect dependencies for Go 1.17 or higher, see https://go.dev/ref/mod#go-mod-file-go.
> build: update `go` directive in `go.mod` to 1.17

- commands.go
This is a followup to https://github.com/go-redis/redis/pull/1928
> fix: add missing Expire methods to Cmdable

- extra/redisotel/redisotel.go
Use full path for tracer name, and decorate traces with the library version
For example, as in other packages:
* https://github.com/open-telemetry/opentelemetry-go-contrib/blob/aad3f901baac5d79791fefb43c81d5b16ca22f99/instrumentation/github.com/gorilla/mux/otelmux/mux.go#L39
* https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7e31ebe040306aee2c826972269f938f9f0e7c34/instrumentation/net/http/otelhttp/config.go#L30
> otel instrumentation name and version

- README.md
https://go.dev/doc/faq#go_or_golang
> fix: rename Golang to Go

- commands.go
- commands_test.go
[This command](https://redis.io/commands/copy) landed in version 6.2.0.
> Add support for COPY command

- universal.go
👋🏾 Hi again,
I found a consumer who is using the `UniversalClient` to support sentinel auth generically, and realized there's another spot where ACL-based auth against sentinels isn't supported. Hope this helps!
> feat: add support for acl sentinel auth in universal client

- internal/pool/conn_check.go
- internal/pool/conn_check_dummy.go
- internal/pool/conn_check_test.go
- internal/pool/export_test.go
- internal/pool/main_test.go
- internal/pool/pool.go
- internal/pool/pool_test.go
- pool_test.go
- sentinel_test.go
- tx_test.go
#2053
check bad conn when getConn from pool and add maxBadConnRetries
> checkConn for badConn and alwaysNewConn(#2053)

- internal/pool/conn.go
useage:
```golang
sshConfig := &ssh.ClientConfig{
User:            "root",
Auth:            []ssh.AuthMethod{ssh.Password("password")},
HostKeyCallback: ssh.InsecureIgnoreHostKey(),
Timeout:         15 * time.Second,
}
client, err := ssh.Dial("tcp", "remoteIP:22", sshConfig)
log.Println(fmt.Errorf("%v", err))
}
cli := redis.NewClient(&redis.Options{
Addr: net.JoinHostPort("127.0.0.1", "6379"),
Dialer: func(ctx context.Context, network, addr string) (net.Conn, error) {
return client.Dial(network, addr)
},
ReadTimeout:  -1,
WriteTimeout: -1,
})
```
> fix: Use redis over SSH channel(#2057)

- result.go
I came across this gap whilst writing a unit test. Hopefully this is the right way to add it!
> Add NewXPendingResult for unit testing XPending

- options.go
- redis.go
Recently encountered a security problem, the running process was scanned to the redis plaintext username and password.
so I was inspired by [CredentialsProvider](https://github.com/eclipse/paho.mqtt.golang/blob/87173763ce056ff2dd4e61c01efae663539178e8/message.go#L115) and added the same method to the redis library.
I use the [cheatengine](https://cheatengine.org/) scanner to run the memory password string.
I block the initConn method, and then use cheatengine to scan the memory of the program. After the initConn method is executed, the password in the memory will be delete immediately.
```go
func (c *baseClient) initConn(ctx context.Context, cn *pool.Conn) error {
if cn.Inited {
return nil
}
cn.Inited = true
username, password := c.opt.Username, c.opt.Password
if c.opt.CredentialsProvider …
```
> Added CredentialsProvider callback for getting username and password

- command.go
In general a client implementation should just rely on the fact that certain parameters are at fixed positions as specified (referenced from https://redis.io/commands/cluster-slots/)
> update cluster slots reply checking logic for Redis 7

- redis.go
fix: #2114 Using `strings.HasPrefix` instead of `equal`
> fix: #2114 for redis-server not support Hello

- cluster.go
Since the error gets swallowed in cmdInfo(), it's important to log it so it's possible for the user to see what the error was.
> cluster: log errors from cmdsInfoCache

- example_test.go
- redis.go
- redis_test.go
The existing context attribute of `conn` was never used.
> refactor: remove unused context attribute from conn

- cluster.go
- redis.go
- ring.go
- sentinel.go
- tx.go
For many types the context attribute was not removed after moving to context propagation via function parameters.
> refactor: remove unused context attributes

- ring.go
- ring_test.go
Fixes #2126 
Tried to figure out how we can fix the #2126 the panic that raises from `func (c *ringShards) Hash(key string)`. And the easiest way is no add missing wiping of `numShard` on `ringShards`, so `c.hash.Get` (where `hash` is nil) will not be called.
Interesting thing that without moving the `c.mu.RUnlock()` in `func (c *ringShards) Hash(key string)` up and to make it deferred test got completely stuck. I think it is connected to the unhandled panic. In a deferred approach mutex will be released no matter how the function exited. So I changed some of the locks to avoid similar problems in other places.
> fix: Handle panic in ringShards Hash function when Ring got closed

- cluster.go
This causes a node to be marked as failing if the client is in READONLY mode
and any error occurs that is either a LOADING error (existing behvaior) or
any non-redis error (e.g. connection error, timeout, etc.).  This prevents that
node from being tried again on the next attempt as usually non-redis errors are
a strong indication that that node is not operational or degraded in some way.
> fix: additional node failures in clustered pipelined reads

- cluster_test.go
Trying to get tests to run locally and getting this red herring panic:
```
go test
Running Suite: go-redis
=======================
Random Seed: 1656897392
Will run 508 of 510 specs
Failure [0.005 seconds]
[BeforeSuite] BeforeSuite 
/Users/mike/src/redis/main_test.go:68
Unexpected error:
<*exec.ExitError | 0x140004b9d60>: {
ProcessState: {
pid: 95236,
status: 256,
rusage: {
Utime: {
Sec: 0,
Usec: 271,
Pad_cgo_0: [0, 0, 0, 0],
},
Stime: {
Sec: 0,
Usec: 975,
Pad_cgo_0: [0, 0, 0, 0],
},
Maxrss: 1441792,
Ixrss: 0,
Idrss: 0,
Isrss: 0,
Minflt: 198,
Majflt: 0,
Nswap: 0,
Inblock: 0,
Oublock: 0,
Msgsnd: 0,
Msgrcv: 0,
Nsignals: 0,
Nvcsw: 2,
Nivcsw: 4,
},
},
Stderr: nil,
}
exit status 1
occurred
/Users/mike/src/redis/main_test.go:72
------------------------------
Panic [0.000 seconds]
[AfterSuite] …
```
> fix: don't panic when test cannot start

- command.go
Fixes https://github.com/go-redis/redis/issues/2160
> fix: fix ClusterSlots to read full metadata

- README.md
> Correct Kvrocks spells and new repo location

- example_test.go
Builds on [existing example code](https://github.com/go-redis/redis/blob/e061db8c13fd6b5e007d73370873026e360719de/example_test.go#L253).
Differs from previous example by passing in "Hash" and not throwing away the `keys`.
`keysFromScan, cursor, err = rdb.ScanType(context.TODO(), cursor, "key*", 10, "hash").Result()`
> docs: another ScanType example with "Hash" as the KeyType

- internal/pool/conn.go
- options.go
This PR revert #2060, which caused #2175.
Fixes #2175.
> fix(internal/pool): call SetDeadline even if timeout is zero

- .github/workflows/build.yml
- .github/workflows/golangci-lint.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- commands.go
- commands_test.go
Fixes the INFO command that was not using all the given sections.
> fix: use all provided sections

- export_test.go
- internal_test.go
- ring.go
- ring_test.go
While working on reducing `ring.SetAddrs` lock contention (see https://github.com/go-redis/redis/pull/2190#discussion_r953040289) I have discovered a race condition between `SetAddrs` and `rebalance` which I would like to fix first and separately.
The change consists of two commits:
- a test to reproduce the race
- the fix 
The fix ensures atomic update of `c.hash` and `c.shards`, otherwise `c.hash` may return shard name that is not in the `c.shards` and cause ring operation panic. 
`BenchmarkRingRebalanceLocked` shows rebalance latency if that is a concern:
```
go test . -run=NONE -bench=BenchmarkRingRebalanceLocked -v -count=10 | benchstat /dev/stdin
name                   time/op
RingRebalanceLocked-8  8.50µs ±14%
```
(Note: it essentially reverts …
> fix: fixes ring.SetAddrs and rebalance race 

- commands.go
- commands_test.go
> feat: add support for SINTERCARD command

- internal_test.go
- ring.go
- ring_test.go
Introduces a new lock to make `SetAddrs` calls exclusive.
This allows release of shards lock for the duration of potentially long `newRingShards` call.
`TestRingSetAddrsContention` observes number of pings increased from <1000 to ~40_000.
See https://github.com/go-redis/redis/pull/2190#discussion_r953040289
Updates #2077
> fix: reduce `SetAddrs` shards lock contention

- .gitignore
- bench_test.go
- ring_test.go
`TestRingSetAddrsContention` caused a lot of test errors, it should be changed to Benchmark.
See #2292
> test: `TestRingSetAddrsContention` changed to Benchmark

- extra/redisotel/metrics.go
- pass attrs by value instead of by reference to the otel histogram `Record` function
- the histograms in the otel sdk perform an in-place sort on the attrs passed into `Record`
- a race condition can occur when separate goroutines concurrently interact with the various redisotel hooks
- this PR converts the dialhook to a read operation which is consistent with the behavior of the other hooks
- side benefit of including the error status attr which is another step towards consistency with the other hooks
> fix(redisotel): correct metrics.DialHook attrs

- commands_test.go
- internal/hscan/hscan.go
- internal/hscan/hscan_test.go
- internal/hscan/structmap.go
- redis.go
Add Scanner interface, scanner is an interface for custom decoding:
See #2298 #2295 #1631 
```go
type TimeValue struct {
time.Time
}
func (t *TimeValue) ScanRedis(s string) (err error) {
t.Time, err = time.Parse(time.RFC3339Nano, s)
return
}
type Data struct {
Name      string     `redis:"name"`
LoginTime TimeValue  `redis:"login_time"`
}
var d Data
err := client.MGet(ctx, "name", "login_time").Scan(&d)
```
> feat(scan): add Scanner interface

- cluster.go
- cluster_test.go
- options.go
- options_test.go
- redis.go
- redis_test.go
- ring.go
- ring_test.go
- sentinel.go
- sentinel_test.go
- universal.go
> feat: add ClientName option

- commands.go
For the v8 version, there is no plan to support redis7, so the redis7 commands are removed: ExpireNX, ExpireXX, ExpireGT, ExpireLT.
> feat: v8 remove redis7 command

- cluster.go
- command.go
- internal/once.go
- internal/proto/scan.go
- options.go
- redis.go
Add a description of the hook, change the parameter name of the function in the Hook interface to next, which is the next hook function to be executed.
Some of the changes are caused by the `go fmt` tool...
> docs: add a description of the hook

- commands.go
- commands_test.go
Add support for [sort read only](https://redis.io/commands/sort_ro/) command, as suggested in discussion https://github.com/go-redis/redis/discussions/2352#discussioncomment-4715670
> feat: add SORT_RO command

- command.go
- internal/proto/reader.go
Fixes https://github.com/go-redis/redis/issues/2355
> fix: read cursor as uint64

- README.md
After testing, in the case of removing the redis-7 api, v9 can pass the test of redis6-server.
We should allow users using redis6 to install go-redis/v9.
@vmihailenco  Do we have other situations where redis6 cannot be used in v9?
> docs: updated "Installation" description in README.md

- extra/rediscensus/rediscensus.go
> fix: Implement `redis.Hook` (v9) for `rediscensus.TracingHook`

- extra/redisotel/README.md
- Update the redisotel example for v9 to match the example at https://redis.uptrace.dev/guide/go-redis-monitoring.html#opentelemetry-instrumentation.
- Fix link to otel example
> docs: Update redisotel example for v9

- internal/pool/pool.go
> feat: remove pool unused fields

- commands.go
- commands_test.go
@monkey92t  I'm learning from LMPOP, so I tried adding the BLMPOP command.  Please help to review whether this PR meets the requirements of the BLMPOP command.
Fix: #2383
> Add support for BLMPOP

- command.go
*fixes 3+ hours of me trying to understand why things don't work* 
see https://github.com/redis/redis/blob/383d902ce68131cf40d6122ce09e305e672e8555/src/t_stream.c#L1456
change the behavior so that if lag is null, the group lag will be set to 0 instead of returning an error
> fix: group lag can be null

- redis.go
See https://github.com/redis/go-redis/issues/2462
dragonfly dont support hello command, it's return "NOAUTH Authentication required" when use Hello command.
> fixed #2462  v9 continue support dragonfly,  it's Hello command return "NOAUTH Authentication required" error

- command.go
- commands.go
- commands_test.go
> Add: Support for COMMAND LIST command

- command.go
- commands.go
- commands_test.go
> Add support for COMMAND GETKEYS & COMMAND GETKEYSANDFLAGS

- commands.go
- commands_test.go
Fixes https://github.com/redis/go-redis/issues/2381
> Add support for acl dryrun command

- cluster_test.go
- command.go
- commands.go
- commands_test.go
> Add support for CLUSTER LINKS command

- cluster_test.go
- command.go
- commands.go
> feat: Add support for CLUSTER SHARDS command

- pipeline.go
- pipeline_test.go
See #2511 
"Do" and "exec" can indeed be easily confused, especially with the existence of http.Client.Do.
> feat: check pipeline.Do to prevent confusion with Exec

- .github/workflows/build.yml
go1.20 was released on 1st Feb 2023, and has good adoption thus better to test against this as well.
If the build cleans, should the go1.18.x be removed or not?
> actions: build on go1.20.x

- example_test.go
The current example will not compile.
> doc: pass ctx in BLpop example for infinite wait time

- redis.go
When the server responds with the RESP protocol and the result is not a normal execution result of the HELLO command, we consider it to be an indication that the server does not support the HELLO command.
The server may be a redis-server that does not support the HELLO command, or it could be DragonflyDB or a third-party redis-proxy. They all respond with different error string results for unsupported commands, making it difficult to rely on error strings to determine all results.
> feat: no longer verify HELLO error messages

- commands.go
> Maintenance : Deprecate FCallRo & add FCallRO

- command.go
- commands.go
- commands_test.go
We can also consider improving `client list` in the future.
fix #2482
> feat: add client info command

- options.go
supplement the default value description for MinIdleConns and MaxIdleConns. Otherwise, every time I see this parameter, I will be a little confused.  
see if the description in the document is reasonable  ？
> docs: update doc of redis option

- cluster.go
- cluster_test.go
- options.go
- options_test.go
- redis.go
- redis_test.go
- ring.go
- ring_test.go
- sentinel.go
- sentinel_test.go
- universal.go
> feat: add protocol option

- command.go
Fix ToBool for bool type.
`b.Client.Do(c, "BF.MEXISTS", "key", "values").BoolSlice()`
got _redis: unexpected type=bool for Bool_
> fix: Fix bool ToBool bug

- commands_test.go
- internal/proto/reader_test.go
commands_test.go:615:50: should use time.Since instead of time.Now().Sub (S1012)
internal/proto/reader_test.go:81:5: should use !bytes.Equal(read, original[:len(original)-2]) instead (S1004)
> chore: fix staticcheck

- README.md
The README currently has a quickstart, but neglects to mention that one can connect using a Redis URI< or how to modify the protocol version behaviour.
This README now contains two changes:
1. Another simple connection using a string
2. An update to the options, indicating that one can control the RESP version, via the  struct.
> Updating the README with connection options

- .github/workflows/build.yml
- Makefile
Bumping the redis test version to rc3 from rc1. Along the way, I also changed the docker image to redis-stack-server, especially given that various PRs starting to be worked on and collected.
Ideally, this is he first phase.
Will help out #2649 and and #2068 until we do something else.
> Bumping redis versions

- .github/workflows/stale-issues.yml
Incorporating the stale issues workflow from redis-py. When an issue is greater than one year old, it will be marked as stale. Should any commenter update the issue with a comment, or even an emoji, the issue will be unmarked as stale.
This should allow us to both over time prune older items, while taking into account community needs and engagement.
> Adding stale issues workflow

- bench_decode_test.go
- cluster.go
- commands.go
- commands_test.go
- options.go
- redis.go
> Identify client on connect

- .github/workflows/build.yml
- .github/workflows/doctests.yaml
> Adding Go 1.21.x for CI coverage

- CONTRIBUTING.md
- README.md
Unlike other projects, we've been missing contributing guidelines, detailing how users can get involved, can report security issues, and the like. These have been inspired by the general guidelines available in other Redis projects.
> Adding CONTRIBUTING guidelines

- commands.go
- probabilistic.go
- redis_gears.go
Today, if we look into `UniversalClient` interface documentation,
https://pkg.go.dev/github.com/redis/go-redis/v9#UniversalClient
it includes the `Cmdable` interface 
https://pkg.go.dev/github.com/redis/go-redis/v9#Cmdable
however we have no mention or link to the methods defined in gears or probabilistic interfaces because such interfaces are private.
> change interfaces probabilistic and redis gears from private to public

- README.md
- internal/pool/pool.go
- options.go
Added the ability to set a connection growth limit when there are not enough connections in the pool using MaxActiveConns
> Added MaxActiveConns

- gears_commands.go
From the Go specification:
> "1. For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Both `Keys` and `Arguments` are `[]string`. Therefore, an additional nil check for before the loop is unnecessary. Example: https://go.dev/play/p/R57hixwdkhX
> refactor(gears): remove redundant nil check

- commands.go
Without it we can't call stream functions from `Cmdable`.
That broke some our code since we rely on `UniversalClient` to abstract from `ClusterClient` and  `Client`. Adding back seems to have solve the isse since those two client do implement `StreamCmdable`.
> Add stream interface back to `Cmdable`

- README.md
The current link returns a 404
> Fix OpenTelemetry link in README

- commands.go
This pull request resolves https://github.com/redis/go-redis/issues/2736 and https://github.com/go-redis/redismock/issues/83
I copied the approach in https://github.com/redis/go-redis/pull/2725, and reviewed the changes in https://github.com/redis/go-redis/pull/2716 for other interfaces we might need to add (didn't find any others).
I added `BitMapCmdable` and sorted the list for readability.
> Add BitMapCmdable to Cmdable.

- .github/CODEOWNERS
This pull request uses the [CODEOWNERS mechanism](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) to define a dedicated owner for the redis.io examples. Ultimately, the people in this file should be able to override CI based on possible false positives in tests, if they are unrelated.
> Creating CODEOWNERS for documentation

- options.go
- ring.go
- sentinel.go
- universal.go
option `DisableIndentity` and `ContextTimeoutEnabled` sometimes are not available or not propagate betweend option types.
BTW I think it is strange that exists an option `CredentialsProvider` but we only use in the _simple_ case, why Universal, Ring or Cluster does not use it?
same for `Limiter`
```go
CredentialsProvider func() (username string, password string)
// Limiter interface used to implement circuit breaker or rate limiter.
Limiter Limiter
```
> Option types must propagage missing fields

- probabilistic.go
the error_rate and capacity parameters should not be optional - corrected
> BUG: BFReserveArgs - error_rate & capacity

- redis.go
- redis_test.go
#2730 
This PR addresses a critical data race issue discovered in `hooksMixin` when `MinIdleConns` is set to a value greater than 1, and `client.AddHook` is used concurrently.
The data race was identified during test, specifically in scenarios where `MinIdleConns` triggers the creation of idle connections in a separate goroutine, while `client.AddHook` modifies the hooks concurrently. This concurrent access and modification of `hooks.dialer` led to a data race.
To resolve this concurrency issue, the following modifications were made:
Introduced a `sync.Mutex` in the `hooksMixin` struct to ensure thread-safe operations.
Implemented locking and unlocking around critical sections in `AddHook` and `dialHook` methods to prevent concurrent read/write conflicts.
Adjusted the clone method in …
> Fix Data Race in hooksMixin When Using MinIdleConns and AddHook

- internal/proto/writer_test.go
This PR fixes `WriteArg` test:
* [Iteration Variables and Closures in "for" Statements](https://golang50shad.es/index.html#closure_for_it_vars)
* conversion from `float32` to `float64` returns the nearest value
> test: fix WriteArg test

- commands_test.go
- sortedset_commands.go
> Change Z member type to string

- command.go
Every time I call this methods, I need to test the output, I have added some samples of the output here. Next time I look at the code comments, I'll know how to use these methods. 😁
e.g.  by printing the data, I knew the difference of the methods in `Cmder`.
```go
...
func (redisHook) ProcessHook(hook redis.ProcessHook) redis.ProcessHook {
return func(ctx context.Context, cmd redis.Cmder) error {
fmt.Printf("starting processing: <%s>\n", cmd)
err := hook(ctx, cmd)
fmt.Printf("finished processing: <%s>\n", cmd)
fmt.Printf("--- %+v \n", cmd.FullName())
fmt.Printf("--- %+v \n", cmd.Args())
fmt.Printf("--- %+v \n", cmd.Name())
fmt.Printf("--- %+v \n", cmd.String())
fmt.Printf("--- %+v \n", cmd.Err())
return err
}
}
...
```
> fix: add Cmder annotation

- bench_decode_test.go
- command.go
- osscluster.go
- ring.go
Whenever a new client connection is established, the client has been excessively sending a "COMMAND" command, even when it's not necessary. I've made a modification so that the "COMMAND" command will only be executed when the `ReadOnly` attribute in `ClusterOptions` is set to `True`. 
The `ReadOnly` attribute enables the execution of read-only commands on slave nodes. This change ensures that the "COMMAND" command is used more efficiently and only when required.
> Execute "COMMAND" command only when readonly 

- README.md
> docs: correct the format error of the url in 'Connecting via a redis url' section

- command.go
- internal/hscan/hscan.go
- internal/hscan/hscan_test.go
- internal/hscan/structmap.go
- json.go
- json_test.go
Sometimes it's convenient to represent your data with structs that contain pointer fields:
```
type Message struct {
hasPermission *bool `redis:"has_permission,omitempty"`
}
```
With nil indicating that the value is absent. 
This change allows go-redis to scan data into pointer fields
> Allow scanning redis values into pointer fields

- command.go
- json.go
Reduce function calling in Result() function.
> return raw value instead of funcation calling in Result()

- commands_test.go
- sortedset_commands.go
Revert #2818 due to a breaking change
> Revert #2818 due to it be a breaking change

- internal/pool/pool.go
Currently there is a race in newConn. This means that any code that uses this client will fail tests with -race flag enabled. This PR fixes this.
> fix ConnPool race in newConn

- osscluster.go
> add CredentialsProvider to ClusterOptions

- osscluster.go
Fix for issues #2959 and #2960
> Fix for issues #2959 and #2960

- bitmap_commands.go
Adding missing interface implementation for Bitfield_RO
Related issue: https://github.com/redis/go-redis/issues/2796
@ofekshenawa @chayim
> Adding BitfieldRo in BitMapCmdable interface

- stream_commands.go
Fix for [issue](https://github.com/redis/go-redis/issues/2982).
> Fix XGroup first pos key

- error.go
- internal/util.go
- internal/util_test.go
If the address in the error is an IPv6 address it adds squared brackets around the host part of the address.
> Handle IPv6 in isMovedError

- CHANGELOG.md
- extra/redisotel/tracing.go
> Remove skipping span creation by checking parent spans

- commands_test.go
> Added test case for CLIENT KILL with MAXAGE option

- commands_test.go
- stream_commands.go
> Add support for XREAD last entry

- command.go
When calling `SetArgs` with `Get: true`, it's useful to be able to read the result as bytes rather than a string (in the same way you would with `Get`). However, `SetArgs` returns `*StatusCmd` (which doesn't implement the `Bytes()` method) rather than `*StringCmd` (which does).
This PR adds a `Bytes()` method to `*StatusCmd` to support this use case.
> Add `(*StatusCmd).Bytes()` method

- commands_test.go
- hash_commands.go
#2991 Supports Hash-field expiration commands, it will be useful to support that in Pipeline.
Also Fix `HExpire` `HExpireWithArgs` expiration, convert it to seconds
> Support Hash-field expiration commands in Pipeline & Fix HExpire HExpireWithArgs expiration

- internal/pool/conn_check.go
- internal/pool/conn_check_test.go
To add TLS connection validation in a connection pool
> add test for tls connCheck #3025

- osscluster.go
- osscluster_test.go
`MOVED` and `ASK` responses during command execution in a cluster mode client are not indicative of transient errors for which the client should gracefully delay before a retry. The current behavior unnecessarily constraints throughput in scenarios where:
* The cluster topology is volatile, e.g. due to active rebalancing (Redis guarantees that keys are moved across nodes atomically during reshard)
* The hash computation yields an incorrect slot for the command, which is at odds with the cached cluster topology state from the most recent `CLUSTER SLOTS` load
These effects are particularly pronounced at scale, when `MinRetryBackoff` is high.
This PR proposes exemption of these classes of errors during the `MaxRedirects` loop.
Consider the following example benchmark, which uses all default …
> Avoid unnecessary retry delay in cluster client following MOVED and ASK redirection

- internal/pool/conn.go
- internal/pool/conn_check.go
- internal/pool/conn_check_dummy.go
- internal/pool/conn_check_test.go
- internal/pool/pool.go
In the current PR, the type assertions of `*tls.Conn` and `TCPConn` to `syscall.Conn` have been reduced.
> feat: reduce the type assertion of CheckConn

- doctests/hash_tutorial_test.go
Go versions of the examples in the [hash datatype page](https://redis.io/docs/latest/develop/data-types/hashes/).
> Doc 4226 hash tces

- doctests/sets_example_test.go
[DOC-4231](https://redislabs.atlassian.net/browse/DOC-4231)
Go versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/sets/).
Note: the last example isn't a testable example (output is non-deterministic), so it doesn't include the `// Output:` comment.
[DOC-4231]: https://redislabs.atlassian.net/browse/DOC-4231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4231 added set datatype examples

- doctests/json_tutorial_test.go
Go versions of the samples in the main [JSON page](https://redis.io/docs/latest/develop/data-types/json/) and the [JSON path page](https://redis.io/docs/latest/develop/data-types/json/path/).
I made a redundant assignment of the `inventory_json` object in the `ExampleClient_setbikes()` function (line 464) to work around a glitch in the way the examples are displayed in the docs page. Also, I've included some long JSON output in the `// Output:` comments in some places. Please let me know if there are better ways to handle these situations.
> DOC-4228 JSON code examples

- .github/workflows/build.yml
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- version.go
Updated package version to represent current version
> Updated package version

- internal/pool/conn.go
- internal/pool/conn_check_test.go
This backports #3138 (related to https://github.com/redis/go-redis/issues/3137) to v9.6 branch. Code changed quite a bit and it's a little trickier to follow but the change should effectively be the same.
> Backport #3138 to v9.6

- doctests/cuckoo_tutorial_test.go
Go version of the example in [this page](https://redis.io/docs/latest/develop/data-types/probabilistic/cuckoo-filter/).
> DOC-4238 added Cuckoo filter examples

- doctests/hll_tutorial_test.go
Go version of the example in [this page](https://redis.io/docs/latest/develop/data-types/probabilistic/hyperloglogs/).
> DOC-4236 added HyperLogLog examples

- doctests/cms_tutorial_test.go
Go version of the example in [this page](https://redis.io/docs/latest/develop/data-types/probabilistic/count-min-sketch/).
> DOC-4239 added Count-min sketch examples

- doctests/bitfield_tutorial_test.go
Go version of the example in [this page](https://redis.io/docs/latest/develop/data-types/bitfields/).
> DOC-4235 added bitfield examples

- doctests/cmds_hash_test.go
Go versions of the examples for [HSET](https://redis.io/docs/latest/commands/hset/) and [HGET](https://redis.io/docs/latest/commands/hget/).
> DOC-4322 added HSET/HGET command page examples

- doctests/cmds_string_test.go
Added a Go version of the [`INCR`](https://redis.io/docs/latest/commands/incr/) command example.
> DOC-4323 added INCR command example

- doctests/cmds_sorted_set_test.go
Go versions of the [`ZADD`](https://redis.io/docs/latest/commands/zadd/) and [`ZRANGE`](https://redis.io/docs/latest/commands/zrange/) command page examples.
> DOC-4324 added ZADD and ZRANGE command examples

- doctests/cmds_generic_test.go
Go examples for [`DEL`](https://redis.io/docs/latest/commands/del/), [`EXPIRE`](https://redis.io/docs/latest/commands/expire/), and [`TTL`](https://redis.io/docs/latest/commands/ttl/).
> DOC-4328 added DEL, EXPIRE, and TTL command examples

- search_commands.go
- search_test.go
I don't know if it's as easy as this, but I found a few struct field names that were misspelled, so I've attempted to correct them.
Closes #3150
> Fix field name spellings

- doctests/stream_tutorial_test.go
Go versions of the examples in [this page](https://redis.io/docs/latest/develop/data-types/streams/).
Note: it's difficult to make the output from the stream commands work well with Go testable examples because of the nondeterministic timestamps. I've tried to work around this by explicitly setting the entry IDs to match the ones from the CLI example where possible. However, for the examples that show `XAdd` without setting the IDs, I've just put the `fmt.Println()` statements inside comments to prevent the output being tested. Doing this also means that some return values from the examples are unused, so I've added an `UNUSED()` function to allow the examples to compile. If there's a better approach to this then please let me know :-)
Also, because I needed to set the IDs, I placed …
> DOC-4232 stream code examples

- doctests/home_json_example_test.go
[DOC-4345](https://redislabs.atlassian.net/browse/DOC-4345)
This is mainly to convert the JSON examples from the [Go client page](https://redis.io/docs/latest/develop/connect/clients/go/#example-index-and-search-json-documents) into testable examples in the client repo. However, it also gives examples for adding options to a query and running an aggregation query. This brings the page in line with the [NRedisStack JSON examples](https://redis.io/docs/latest/develop/connect/clients/dotnet/#example-indexing-and-querying-json-documents). 
Note that the Go doc page needs some extra text to go around the new examples. I'll add them to the docs when this PR is accepted.
[DOC-4345]: https://redislabs.atlassian.net/browse/DOC-4345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
> DOC-4345 added JSON samples for home page

- redis.go
- redis_test.go
The immediate symptom this PR attempts to address: during periods of transient server connectivity errors, go-redis commands time out after upwards of 60s (or more), even though the socket read/write timeouts are 3s and the context timeout on the commands is 1s. We have root caused this bug to lock contention in the connection pool's lazy dialer.
There is a mutual exclusion lock in `DialHook`, which allows only one server dial to occur at the same time. In the event of server connectivity errors, this causes unbounded connection queueing under highly concurrent workloads.
Consider, for example, a concurrent workload with the default dial timeout of 5s, and an unresponsive server endpoint. During this period, all dials are timing out.
1. The connection pool is empty, or all connections are …
> Eliminate redundant dial mutex causing unbounded connection queue contention

- command.go
- osscluster_test.go
This PR is mildly related to #3048.
The cluster client uses the command type to determine the expected key position in the command arguments slice to compute the hash slot. This enables the client to properly send the command to the node that owns that slot, according to the cached cluster topology state.
For generic commands assembled with the `Do()` API, the logic falls back to assuming the key is at position 1. Though this is a reasonable assumption, it depends on the argument to be of `string` type; `[]byte` type arguments are not converted to strings, which results in an incorrect slot computation, thus forcing (in most cases) a double round trip caused by response to a `MOVED` redirection.
This PR adds a `[]byte` type case for key string serialization, so that the generic commands …
> Recognize byte slice for key argument in cluster client hash slot computation

- search_commands.go
- search_test.go
In search_commands.go, if the `SortByWithCount` option is true, the query argument that is added is misspelled. it is currently `WITHCOUT`, but should be `WITHCOUNT`.
`if options.SortByWithCount {
queryArgs = append(queryArgs, "WITHCOUNT")
}`
This change fixes the spelling.
> SortByWithCount FTSearchOptions fix

- doctests/pipe_trans_example_test.go
[DOC-4560](https://redislabs.atlassian.net/browse/DOC-4560)
This is basically to provide examples for Go transactions/pipes that are similar to the [Python examples](https://redis.io/docs/latest/develop/clients/redis-py/transpipe/) (although the structure of the code for Go is a bit different, of course).
[DOC-4560]: https://redislabs.atlassian.net/browse/DOC-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4560 pipelines/transactions example

- doctests/cmds_hash_test.go
[DOC-4449](https://redislabs.atlassian.net/browse/DOC-4449) and [DOC-4454](https://redislabs.atlassian.net/browse/DOC-4454)
I've also made the test for the hset example deterministic by not relying on the order of the hash keys. I originally used the [Collect](https://pkg.go.dev/slices@master#Collect) and [Keys](https://pkg.go.dev/maps#Keys) standard lib functions to do this. However, they have only been added recently (Go 1.23.0), so they don't pass the CI. Let me know if there's a better way to handle this without Collect and Keys.
[DOC-4449]: https://redislabs.atlassian.net/browse/DOC-4449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOC-4454]: https://redislabs.atlassian.net/browse/DOC-4454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
> DOC-4449 hash command examples

- doctests/sets_example_test.go
While executing the tests locally some failed due to slices not being returned in the order that was expected. Ordering the result before printing fixes this.
> Order slices of strings to be sure what the output of Println in doctests will be.

- .gitignore
- command.go
- docker-compose.yml
- main_test.go
Redis 8.0 introduces new key `io-thread` in the response
for `client info`. The key needs to be parsed. If an unknown key
is observed, the client will return an error.
This PR also introduces the 8.0-M3 build in the docker compose and a small improvement to the readability.
> fix(command): add missing `io-thread` key in `client info`

- .gitignore
- command.go
- commands_test.go
- main_test.go
- search_commands.go
- search_test.go
> feat(tests): validate that ConfigSet and ConfigGet work with Modules

- acl_commands.go
- acl_commands_test.go
- commands_test.go
> feat(command): add ACL commands, validate module categories exist

- search_commands.go
- search_test.go
> fix(aggregate, search): ft.aggregate bugfixes

- options.go
- osscluster.go
- universal.go
- universal_test.go
fixes https://github.com/redis/go-redis/issues/3261
> fix: add unstableresp3 to cluster client

- commands_test.go
Add tests for `INFO` , `INFO modules`, `INFO everything`, `INFO search` with Redis CE 8
> test: add test for `INFO` in RCE 8

- search_commands.go
- search_test.go
`Limit` was only set when `LimitOffset > 0` which caused the bug shown in  https://gist.github.com/gariel/2af35a6a87c4653dbdebd61b0fd78441
> fix(search): if ft.aggregate use limit when limitoffset is zero

- command.go
I'm validating an idea for my linter. I checked the top 2500 projects on github and found this.
All project result can be found here -> https://github.com/alingse/sundrylint/issues/7
I think move the `regexp.MustCompile` out has two advantages
1. Performance benefits
2. Fail early with faulty regexp string
> move regexp.MustCompile close to call

- .github/wordlist.txt
- .github/workflows/golangci-lint.yml
- .golangci.yml
- README.md
- command.go
- commands_test.go
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- hash_commands.go
- options.go
- osscluster.go
- osscluster_test.go
- redis.go
- redis_test.go
- search_commands.go
- search_test.go
- universal.go
- universal_test.go
- version.go
- Recognize byte slice for key argument in cluster client hash slot computation (#3049)
- fix(search&aggregate):fix error overwrite and typo  #3220 (#3224)
- fix: linter configuration (#3279)
- fix(search): if ft.aggregate use limit when limitoffset is zero (#3275)
- Reinstate read-only lock on hooks access in dialHook to fix data race (#3225)
- fix: flaky ClientKillByFilter test (#3268)
- chore: fix some comments (#3226)
- fix(aggregate, search): ft.aggregate bugfixes (#3263)
- fix: add unstableresp3 to cluster client (#3266)
- Fix race condition in clusterNodes.Addrs() (#3219)
- SortByWithCount FTSearchOptions fix (#3201)
- Eliminate redundant dial mutex causing unbounded connection queue contention (#3088)
- Add guidance on unstable RESP3 support for RediSearch commands to README …
> release: 9.7.1 patch

- universal.go
- universal_test.go
- This is required because Elasticache supports setting up cluster mode with configuration endpoint. So the check len(Addrs) > 1 is not enough for determining cluster mode.
- If IsClusterMode is true, the client will be created as a cluster client.
> feat: support Elasticache cluster mode by setting IsClusterMode in config

- doctests/query_range_test.go
by sorting the results that we would like to get from redis we make sure the exampele test passes.
p.s. we are sorting by price but there are items with identical prices the data itself may need to change a bit. Let's see if we experience any flakiness with this setup.
> fix(test): sort results in example test

- error.go
- osscluster.go
- osscluster_test.go
Issue: After upgrading from 9.5.1 to 9.7.0, we noticed the spikes in connections to Master/ Primary nodes and also reads are happening from Master nodes. Also noticed increase in pool_conn_total_current metrics. 
Environment: AWS Cloud, Elasticache Redis with Cluster Mode
Cause: After debugging, we noticed that nodes are marked as failed when the `context.Cancelled` error is raised https://github.com/redis/go-redis/blob/930d904205691ff06104fcc3ac108177077def35/osscluster.go#L1324.  This is introduced in v9.5.2. 
We tested this by deploying the change from my Fork and noticed improvements. Elasticache Cluster Current Connections Screenshot:
FYI: My first PR to go-redis. Happy to fix if any concerns.
> fix: Fixed issue with context cancelled error leading to connection spikes on Primary instances

- extra/rediscmd/rediscmd.go
- extra/redisotel/tracing_test.go
This pull request removes previously imposed limits on command handling in the Redis command processing module and adds tests for tracing hooks involving long commands and arguments. In the `rediscmd.go` file, the constants limiting command count, argument count, and argument length have been removed, allowing the processing of all elements in the input. In the `tracing_test.go` file, two new tests are introduced to verify that the tracing hooks correctly capture spans for long commands and pipelines.
> Show Whole Command on Tracing

- README.md
- bench_decode_test.go
- options.go
- osscluster.go
- redis.go
- redis_test.go
- ring.go
- sentinel.go
- universal.go
- handle non-redis errors on setinfo in `connInit`
- introduce new (duplicate) flag `DisableIdentity` for `DisableIndentity` to work side by side, addressing the misspelled flag, prior to `v10`
> fix: handle network error on SETINFO

- example/hset-struct/go.sum
- universal.go
- universal_test.go
It would be nice to add suport of FailoverClusterClient into UniversalClient constructor.
> Add FailoverClusterClient support for Universal client

- .github/workflows/golangci-lint.yml
`golangci` introduced `version` as a required field in the configuration jsonschema as they just had a major release (https://ldez.github.io/blog/2025/03/23/golangci-lint-v2/). 
The latest jsonshema was picked up by the github action we are using and the config verification failed. 
Skipping the verification of the configuration for now before they release new major version of the github action as well.
> chore: disable verifying golangci configuration

- README.md
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/hset-struct/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- version.go
Update README.md
Update versions.
> Sync master with v9.8.0-beta.1

- .github/actions/run-tests/action.yml
- .github/workflows/build.yml
- search_test.go
- Update docker mappings to use the `RC1-pre` image for Redis 8 CE
> Test agains Redis 8.0-RC1

- search_commands.go
- search_test.go
Adding a new boolean flag, CountOnly, to the FTSearchOptions struct to decouple count-only behavior from the default limit parameters.
Previously, it wasn't possible to input 0 0 for LimitOffset and Limit  Now, with the CountOnly flag, users can explicitly signal a count-only query.
When CountOnly is set to true, the FT.SEARCH command builder appends LIMIT 0 0, ensuring that only the total count of matching documents is returned. When CountOnly is false, the provided LimitOffset and Limit values are used as usual.
> Fix FT.Search Limit argument and add CountOnly argument for limit 0 0

- hash_commands.go
The function was removed by mistake from the interface. The implementation is present.
> fix: add missing command in interface

- sentinel.go
- sentinel_test.go
https://github.com/redis/go-redis/issues/3339
> Use DB option in NewFailoverClusterClient

- doctests/home_json_example_test.go
[DOC-5102](https://redislabs.atlassian.net/browse/DOC-5102)
There is also be some extra text ready to add to the [JSON search example page](https://redis.io/docs/latest/develop/clients/go/queryjson/) when this is example is approved and merged.
[DOC-5102]: https://redislabs.atlassian.net/browse/DOC-5102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5102 added CountOnly search example for docs

- internal_test.go
- osscluster.go
Added selection of the correct slot for the CLUSTER COUNTKEYSINSLOT command based on the argument.
This allows to make a request for the number of keys in a slot not for all shards, but for the necessary one.
> Use correct slot for COUNTKEYSINSLOT command

- sentinel.go
- sentinel_test.go
Switch from sequential sentinel query to concurrent query to avoid context exhaustion and connect to new master redis after redis failover
> Ensure context isn't exhausted via concurrent query as opposed to sentinel query

- sentinel.go
- Make sure all sentinel errors are reported if the `masterAddr` was not resolved.
- Resolving the `masterAddr` concurrently may result in read from `errCh` before read from `done` => first check if the `masterAddr` was resolved, and then proceed to report errors.
> fix: better error handling when fetching the master node from the sentinels

- doctests/home_json_example_test.go
[DOC-5111](https://redislabs.atlassian.net/browse/DOC-5111)
This is to extend the examples in [this page](https://redis.io/docs/latest/develop/clients/go/queryjson/) to include hash search. The text of the page will also be reworked a bit to explain the differences with hashes.
[DOC-5111]: https://redislabs.atlassian.net/browse/DOC-5111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5111 added hash search examples

- hash_commands.go
Update HExpire to notе that the commands are available since Redis 7.4
> update HExpire command documentation

- pubsub.go
> fix: struct `PubSub` isn't concurrency-safe

- osscluster.go
- redis.go
- redis_test.go
- ring.go
- sentinel.go
- universal.go
Client creation should panic when options are nil.
Resolves #3358
> feat(options): panic when options are nil

- internal/pool/pool.go
- internal/pool/pool_test.go
Hi! This PR adds connection waiting statistics. These statistics are useful for tuning pool parameters. Inspired by [redigo stats](https://github.com/gomodule/redigo/blob/a60882bf9e77d7f428bdfa7e27516979d833f663/redis/pool.go#L275-L281).
I removed doctests with Go 1.18 due to `atomic.Int64` usage.
> feat: add connection waiting statistics

- .github/actions/run-tests/action.yml
- .github/workflows/build.yml
- main_test.go
- search_test.go
update redis testing image to version 8.0.1
> ci(redis): update to 8.0.1

- helper/helper.go
- internal/util/convert.go
- internal/util/convert_test.go
- search_test.go
- Added utils/convert.go with public wrappers
- Added tests in utils/convert_test.go
closes #3206
> utils: export ParseFloat and MustParseFloat wrapping internal utils

- internal/util/strconv_test.go
This pull request adds unit tests for the `util` package, specifically covering the following functions:
* `Atoi`
* `ParseInt`
* `ParseUint`
* `ParseFloat`
These tests validate both valid and invalid input cases to improve confidence in parsing logic and ensure correct error handling.
---
The tests include:
* Basic positive and negative integer conversions
* Base-10, base-16, and base-36 parsing
* Unsigned integers and invalid (e.g., negative for uint)
* Float parsing, including special values like `NaN`
* Expected errors for malformed or invalid inputs
---
Adding test coverage for utility parsing functions helps ensure correctness and guards against regressions in future changes. These are low-level helpers that are widely used internally, so ensuring their reliability is critical.
---
> test(util): add unit tests for Atoi, ParseInt, ParseUint, and ParseFloat

- ring.go
* reduce unnecessary copy operations in file `ring.go`
* remove redundant hash operation in file `ring.go`
In struct `Ring`, the size of shards can be up to 100 (https://github.com/redis/go-redis/pull/2190#discussion_r953040289),  in this case, a copy operation is called for each heartbeat, and approximately 3.1 KB data are copied. This is a waste of CPU resources. So avoiding copy operations yields benefits.
The pr #2931 reported a race here, but ​​there actually isn't one. Because every time we get the slice `c.shards.list`, we don't change slice itself, we only use `c.shards.list[i].Client` which is concurrency-safe.
> perf: avoid unnecessary copy operation

- osscluster.go
- ring.go
Apologies - in PR #3382 I cleaned up unused function params but overlooked these two.
@ndyakov
> chore: remove unused param

- command.go
- commands_test.go
> xinfo-groups: support nil lag in XINFO GROUPS

- osscluster.go
When a new slave node is added to a Redis cluster, it enters a loading state while it synchronizes data from its master. If the client has `ReadOnly=true` enabled, it may route read operations to this loading slave node, which can result in nil values or errors being returned to the application.
closes #3222 
This PR adds logic to detect when a slave node is in the loading state (by checking for LOADING errors) and temporarily excludes such nodes from the read distribution until they're ready to serve requests.
> Fix: Prevent routing reads to Redis slave nodes in loading state

- ring.go
- ring_test.go
This PR adds two new methods to the `Ring` client that provide access to individual shard clients, addressing the need to create dedicated connections (e.g., PubSub) for each shard.
When using Redis Ring with PubSub connections, users need to create separate PubSub connections for each shard because PubSub connections enter a special mode and cannot be used for other Redis operations. Currently, there's no way to access the underlying shard clients directly, making it impossible to pre-create and reuse PubSub connections [related issue](https://github.com/redis/go-redis/issues/3341)
This PR introduces two new public methods to the `Ring` struct, users can pre-create and reuse PubSub connections per shard
1. `GetShards() []*Client`
- Returns a list of all currently active shard clients
- …
> feat(ring): add GetShardClients and GetShardClientForKey methods to Ring for shard access

- RELEASE-NOTES.md
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/hset-struct/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- version.go
- Add release notes
- Update dependencies and version.go
> release(go-redis): v9.9.0

- result.go
When I was developing for another project, I ran into a situation in which I needed to test `ZMScore` in my unit tests.
However, I found out that there existed no helper method that returned a mocked `FloatSliceCmd` with a populated result.
After digging into the code, it looked to me like there existed `NewStringSliceResult`, `NewBoolSliceResult`,  but no `NewFloatSliceResult` method.
This PR simply adds that method so that it can be used for testing in other projects.
> Add the missing NewFloatSliceResult for testing

- command.go
- commands.go
- unit_test.go
- vectorset_commands.go
- vectorset_commands_integration_test.go
- vectorset_commands_test.go
vectorset commands: https://redis.io/docs/latest/develop/data-types/vector-sets/
> feat: support vectorset

- .github/workflows/doctests.yaml
- Makefile
- doctests/Makefile
- doctests/main_test.go
- doctests/vec_set_test.go
[DOC-5078](https://redislabs.atlassian.net/browse/DOC-5078)
Go versions of the examples in the [main vector set page](https://redis.io/docs/latest/develop/data-types/vector-sets/), and also the [performance](https://redis.io/docs/latest/develop/data-types/vector-sets/performance/) and [memory optimisation](https://redis.io/docs/latest/develop/data-types/vector-sets/memory/) pages.
Note: some of the tests fail but I guess these are running against the previous version of Redis without vector set support? Is there any way to skip the doc tests in these cases?
[DOC-5078]: https://redislabs.atlassian.net/browse/DOC-5078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-5078 vector set examples

- error.go
- osscluster.go
- osscluster_test.go
`go-redis` should not try to do some magic and support multi slot transactions. Such cross slot operations are not supported by the database server for a reason and what the library can do is to report an error to the user as soon as possible. 
Althought this changes the behaviour it is considered a bugfix.
closes #3019
> [CAE-1028] fix(txpipeline): should return error on multi/exec on multiple slots

- extra/redisotel/config.go
- extra/redisotel/tracing.go
- extra/redisotel/tracing_test.go
Good day,
While profiling our application we noticed that more time then we expected was spend in `funcFileLine` called as part of the redisotel tracing. In our scenario we don't actually need the `code.function`, `code.filepath` and `code.lineno`  attributes for which `funcFileLine` is called, so I created this PR. 
This PR introduces a new option for redisotel tracing called `WithCallerEnabled` using it allows one to disable the collection of the `code.function`, `code.filepath` and `code.lineno` tracing attributes. When setting `WithCallerEnabled(false)` overall performance is increased as the "expensive" `runtime.Callers` and `runtime.(*Frames).Next` calls are no longer needed.
Thank you for reviewing this PR and please let me know what you think!
Have a great day!
> feat(redisotel): add WithCallerEnabled option

- ring.go
- ring_test.go
https://github.com/redis/go-redis/issues/3402
> [ISSUE-3402]: Ring.Pipelined return dial timeout error

- .github/workflows/stale-issues.yml
**Added Dual-Tier Stale Policy:**
- Standard timeline: Issues/PRs still follow 365→30 day cycle
- Accelerated timeline: Issues with needs-information label now get 30→7 day cycle
- Separate jobs handle each policy independently
- Detailed messages explaining why items are marked stale and how to keep them open
- Exempt labels: `no-stale`, `needs-information` (for standard policy)
- Only `no-stale` exempt for PRs (`needs-info` doesn't apply)
> Improve stale issue workflow

- osscluster.go
- redis.go
- sentinel.go
- replace two similar functions `appendUniqueNode` and `appendIfNotExists` with a generic function.
- simplify the implementation of the `get` method in `clusterNodes`.
- keep the member name `_generation` of `clusterNodes` consistent with other types.
- rename a data member `_masterAddr` to `masterAddr`.
> improve code readability

- .github/actions/run-tests/action.yml
- .github/workflows/build.yml
- RELEASE-NOTES.md
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/hset-struct/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- version.go
- update the release notes
- update dependencies in extra package
- update version
- update ci image to use 8.2
> chore(release): 9.12.0 / redis 8.2

- options.go
- osscluster.go
- osscluster_test.go
- sentinel.go
- universal.go
This PR implements a fully configurable FailingTimeoutSeconds option for Redis cluster clients, addressing #2928 and completing the work initially started by @trend-shino-wu.
Closes #2928
> Clean failing timeout implementation

- README.md
> Update the introduction to running tests in README.md

- extra/redisotel/metrics.go
Follow up to #3493
Apologies for missing this the first time. It registers the new metrics so we can send them.
> fix(otel): register wait metrics

- pipeline.go
- pipeline_test.go
Addresses https://github.com/redis/go-redis/issues/3503
Changed `Process` to use `BatchProcess` since it's an edge case and DRY
> Added batch process method to the pipeline

- osscluster.go
- redis.go
Fixes #2871 
Two separate issues:
- The first one reported by @AvyChanna was related to first error which was not supposed to be retried, especially if it is a client error before being able to get a connection, to not be assigned to the commands.
- The second one, reported by @tptodorov, was related to TxPipeline which was ignoring errors when queueing commands.
> fix: SetErr on Cmd if the command cannot be queued correctly in multi/exec

- scripts/tag.sh
Improved the tag.sh script to ensure that all internal dependencies in the go.mod files are using the currently tagged version
> feat(tag.sh): Improved resiliency of the release process

- RELEASE-NOTES.md
- example/del-keys-without-ttl/go.mod
- example/hll/go.mod
- example/hset-struct/go.mod
- example/lua-scripting/go.mod
- example/otel/go.mod
- example/redis-bloom/go.mod
- example/scan-struct/go.mod
- extra/rediscensus/go.mod
- extra/rediscmd/go.mod
- extra/redisotel/go.mod
- extra/redisprometheus/go.mod
- go.mod
- version.go
https://pkg.go.dev/ shows that v9.15.0 was released alongside v9.15.0-beta.2 with both versions being identical.
Retract v9.15.0 to avoid confusion
> Retract 9.15.0
